### ISSUE TITLE
Keep Repeated Builds in Stash when off not working as expected

### ISSUE THREAD

**Issue by jwstric2** [jenkinsci/stashnotifier-plugin#105]
Stash Notifier Version:  1.9.0
Jenkins Core:  1.651

We had an infrastructure failure the other day during a pull request build.  This of course caused the build to fail and stash was notified of the failure.  Our team issued for stash to "Re-Trigger Build".  After it built the build status was still showing as failed.

In our stash notification config we have the flag "Keep repeated builds in Stash" off (set to false as seen in the config.xml and jenkins view attachments).  However, it appears that the plugin is still adding a unique key for each build instead of updating.  Seems that Stash/Bitbucket would have some setting to use latest build results for the commit (we are investigating that) but as part of this we are pondering why the plugin is adding a unique key to each one.  See below for example call that show a unique key was created by Stash.

![bitbucket_stash_notify_settings](https://cloud.githubusercontent.com/assets/7996149/14679064/5b6ec67c-06e6-11e6-846f-55af37f5a881.jpg)

GET <base url>/rest/build-status/1.0/commits/d1a922d81feb2b59b226d75b942bc88c26c90d00

{"size":4,"limit":100,"isLastPage":true,"values":[{"state":"SUCCESSFUL","key":"trigger-37-https:\\/\\/triad-jenkins.cisco.com\\/","name":"SysadminRepo / trigger #37","url":"https://triad-jenkins.cisco.com/job/SysadminRepo/job/trigger/37/","description":"built by Jenkins @ https://triad-jenkins.cisco.com/","dateAdded":1461158685913},{"state":"SUCCESSFUL","key":"trigger-36-https:\\/\\/triad-jenkins.cisco.com\\/","name":"SysadminRepo / trigger #36","url":"https://triad-jenkins.cisco.com/job/SysadminRepo/job/trigger/36/","description":"built by Jenkins @ https://triad-jenkins.cisco.com/","dateAdded":1461158650775},{"state":"SUCCESSFUL","key":"trigger-35-https:\\/\\/triad-jenkins.cisco.com\\/","name":"SysadminRepo / trigger #35","url":"https://triad-jenkins.cisco.com/job/SysadminRepo/job/trigger/35/","description":"built by Jenkins @ https://triad-jenkins.cisco.com/","dateAdded":1461156075920},{"state":"FAILED","key":"trigger-34-https:\\/\\/triad-jenkins.cisco.com\\/","name":"SysadminRepo / trigger #34","url":"https://triad-jenkins.cisco.com/job/SysadminRepo/job/trigger/34/","description":"built by Jenkins @ https://triad-jenkins.cisco.com/","dateAdded":1461155872088}],"start":0}

To reproduce this issue:

1.  Create a dummy bug branch and make a small change to something like README file
2.  Modify the pull request jenkins job to fail (simulating an infrastructure fail) by adding an "execute shell" task with "exit 1".
3.  Open a Pull request (which will notifiy Jenkins in our case; we have trigger of open/reopen/source or dest change)
4.  Pull request fails
5.  Modify job to now pass by removing "exit 1" "execute shell".
6.  The builds are now passing but still shows as not passing, and a list of builds are showing up instead of being  a unique key

The logic possibly in question is below at:    

`
private String getDefaultBuildKey(final AbstractBuild<?, ?> build) {
    StringBuilder key = new StringBuilder();

    key.append(build.getProject().getName());
    if (includeBuildNumberInKey
        || getDescriptor().isIncludeBuildNumberInKey()) {
      key.append('-').append(build.getNumber());
    }
    key.append('-').append(Jenkins.getInstance().getRootUrl());

    return key.toString();
  }

`

**Comment by scaytrase** [comment]
the "keep repeated builds" flag could be also enabled at global level. check it, please

**Comment by jwstric2** [comment]
@scaytrase  Thanks, after reading the specs I understood a bit more about getDescriptor() and the global config options.  The code logic makes sense now and to your comment; yes when we disabled it globally it works as expected (overriding the existing key).

Thanks,
Jonathan
