### ISSUE TITLE
Use plugin on Jenkins 2.0 multibranch pipeline

### ISSUE THREAD

**Issue by tmds** [jenkinsci/stashnotifier-plugin#106]
I don't know how to setup the plugin on a multibranch pipeline.
The configuration page does not have a 'Post-build Actions section'.

**Comment by scaytrase** [comment]
Duplicate of #92

**Comment by marcusphi** [comment]
To me it seems like the Bitbucket (Stash) notofocation is automatic when using the bitbucket branch source plugin for the multibranch pipeline.

**Comment by tmds** [comment]
@marcusphi I didn't know about that plugin. Can you set it up to use a local stash/bitbucket server as well?

**Comment by marcusphi** [comment]
Yes. The Bitbucket server URL is configurable.

Marcus Philip
+46 70 767 46 77
Twitter: @marcus_phi
