### ISSUE TITLE
Custom comment to stash

### ISSUE THREAD

**Issue by kashjs** [jenkinsci/stashnotifier-plugin#113]
Hello,

We use this plugin with our UI deployments. We build all the branches and deploy them even if build fails for easy prototyping/demoing. 

It seems like this plugin only lets us Post build status to stash. It would be nice if we can add additional/custom information to the comment to stash. Immediate thing that we need is ability to also post the url where branch has been deployed. Along with some custom message. Is it possible to get this support?

Thanks,
Kash

**Comment by scaytrase** [comment]
This plugin automatically fetches the description of the build (not of the job, but the build) to the build message, you can use it to enrich your data
