### ISSUE TITLE
Odd behavior with macro expansion

### ISSUE THREAD

**Issue by twllight** [jenkinsci/stashnotifier-plugin#117]
Hello,

I've been running into some issues with the StashNotifer-plugin. I checkout two different git repositories within my jenkins build and want to notify on only one of the builds. I'm attempting to use the EnvInject plugin to create the variable with the SHA value however . I keep seeing the following:

_14:15:56 org.jenkinsci.plugins.tokenmacro.MacroEvaluationException: Unrecognized macro 'FOO' in '$FOO'
14:15:56 	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expand(TokenMacro.java:207)
14:15:56 	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:246)
14:15:56 	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:232)
14:15:56 	at org.jenkinsci.plugins.stashNotifier.StashNotifier.lookupCommitSha1s(StashNotifier.java:287)
14:15:56 	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:247)
14:15:56 	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:208)
14:15:56 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
14:15:56 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
14:15:56 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
14:15:56 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
14:15:56 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
14:15:56 	at hudson.model.Run.execute(Run.java:1763)
14:15:56 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
14:15:56 	at hudson.model.ResourceController.execute(ResourceController.java:98)
14:15:56 	at hudson.model.Executor.run(Executor.java:410)__

Here is my Variable Injection:

_14:10:41 FOO=`git ls-remote ssh://git@stash:7999/techops/puppet.git origin ${branch} | cut -f1`
14:10:41 echo $FOO
14:10:41 
14:10:41 [/tmp] $ /bin/sh -xe /tmp/hudson6224827593939517672.sh
14:10:41 ++ git ls-remote ssh://git@stash:7999/techops/puppet.git origin feature-grk-nginx-forward
14:10:41 ++ cut -f1
14:10:41 + FOO=d6147261da5d1c8b02cf818edb26588fefd41c98_

I have the sha here as represented by FOO however the StashNotifier-Plugin doesn't seem to be able to read the variable.

**Comment by twllight** [comment]
I am running plugin version 1.10.4 as well

**Comment by scaytrase** [comment]
Not sure you can do this without something like https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin
Do you have one?

**Comment by twllight** [comment]
Yes,

I'm using the EnvInject plugin, here is the relevant code:
_15:57:54 [EnvInject] - Loading node environment variables.
15:57:54 [EnvInject] - Preparing an environment for the build.
15:57:54 [EnvInject] - Keeping Jenkins system variables.
15:57:54 [EnvInject] - Keeping Jenkins build variables.
15:57:54 [EnvInject] - Executing and processing the following script content: 
15:57:54 FOO=`git ls-remote ssh://git@stash:7999/techops/puppet.git origin ${branch} | cut -f1`
15:57:54 echo $FOO
15:57:54 
15:57:54 [/tmp] $ /bin/sh -xe /tmp/hudson7073419532170432272.sh
15:57:54 ++ git ls-remote ssh://git@stash:7999/techops/puppet.git origin feature-grk-nginx-forward
15:57:54 ++ cut -f1
15:57:55 + FOO=9b8679380458ac2f56d40b183de68dbd7e33870e
15:57:55 + echo 9b8679380458ac2f56d40b183de68dbd7e33870e
15:57:55 9b8679380458ac2f56d40b183de68dbd7e33870e
15:57:55 [EnvInject] - Script executed successfully._

EnvInject does show the variable being set, further down I can see the var if i run the printvar shell command and it does show.

**Comment by scaytrase** [comment]
Looks odd. I'll try to reproduce.

**Comment by twllight** [comment]
ok sounds good, reach out and ill provide anything needed: Jenkins version 1.655 btw

**Comment by scaytrase** [comment]
2.x gives another error, but cause is the same. thanks for reporting

**Comment by scaytrase** [comment]
@twllight it looks like something wrong with the Token Macro Expansion plugin iteslf, as I getting the same error with Description Setter Plugin. Looks like the macro plugin does not receive tokens from outside the build. That works well before and stopped recently


https://wiki.jenkins-ci.org/display/JENKINS/Description+Setter+Plugin

**Comment by scaytrase** [comment]
I've created an issue to token macro https://issues.jenkins-ci.org/browse/JENKINS-37238

**Comment by scaytrase** [comment]
The problem is in the token macro plugin - beta version. just revert it to the 1.x stable and everything should go OK

**Comment by twllight** [comment]
Thank you so much for sussing that out!
