### ISSUE TITLE
Plugin Showing only failed builds

### ISSUE THREAD

**Issue by twllight** [jenkinsci/stashnotifier-plugin#119]
Hello,

When using the stashnotifier plugin, failed builds always show up on the stash PR page. Even when a passing build happens afterwards. Are there settings or configuration options that are required for the plugin to only show the newest build in a PR?

**Comment by twllight** [comment]
StashNotifer version = 1.10.4

**Comment by scaytrase** [comment]
Looks like you have option `keep repeating builds in Stash` enabled. With this option older build status are not overwritten, but appended.

**Comment by pecak2** [comment]
I just checked and it appears that the 'keep repeated builds in stash' option is not enabled for the project. Could there be another cause for this?

**Comment by pecak2** [comment]
nor is it enabled in system settings

**Comment by scaytrase** [comment]
how many build records do you have for the latest commit?

**Comment by sdmoralesma** [comment]
Did you check that the `key` in both commits is the same?, if not, you are probably facing this issue: https://github.com/jenkinsci/stashnotifier-plugin/issues/16

**Comment by pecak2** [comment]
Thanks for posting that link, it had some helpful information

**Comment by scaytrase** [comment]
Sure, it won't. The key is unique within the commit and different key results in several builds for commit, while the single key will overwrite(update) previous build with *the same* key. That's how the `INPROGRESS`|`SUCCESSFULL` works.

Having `Keeping repeated builds` checked appends build number to the key, so the keys are different each time. Unchecking this will make *further* build keys the same, but this will not purge the previous builds for commit, you have to make a dummy commit (i.e amend with new date)

**Comment by scaytrase** [comment]
Is this issure resolved?

**Comment by pecak2** [comment]
yes thank you, you can close this out
