### ISSUE TITLE
Feature request: decouple from currentBuild.result

### ISSUE THREAD

**Issue by philbert** [jenkinsci/stashnotifier-plugin#122]
Stash and Jenkins have different understandings of a build status, so it is unfortunate that the StashNotifier is tightly coupled to the value of ```currentBuild.result```.

[Stash understands the values of "INPROGRESS", "SUCCESSFUL" and "FAILURE"](https://developer.atlassian.com/stash/docs/latest/how-tos/updating-build-status-for-commits.html), however, 
[Jenkins understand the values of "SUCCESS", "FAILURE", "UNSTABLE", "NOT_BUILT" and "ABORTED"](http://javadoc.jenkins-ci.org/hudson/model/Result.html)

One should not have to modify the jenkins build result to post a result to stash. 

I request a feature that would allow me to do the equivalent of:
```
step([$class: 'StashNotifier', buildResult: 'INPROGRESS']) 
step([$class: 'StashNotifier', buildResult: 'SUCCESSFUL']) 
step([$class: 'StashNotifier', buildResult: 'FAILURE']) 
step([$class: 'StashNotifier', buildResult: null])   // to clear a build that was previously marked 
                                                     // INPROGRESS but was aborted or yields no result
```

Right now in order to retain my jenkins build result of "UNSTABLE" I need to write code like this, and I still need some other solution to handle "ABORTED" builds.
```
    if (currentBuild.result == null) {
        currentBuild.result = "SUCCESS"
        step([$class: 'StashNotifier'])   
    } else if ( currentBuild.result == "UNSTABLE") {
        currentBuild.result = "FAILED"
        step([$class: 'StashNotifier'])   
       // and this doesn't actually work for some reason, the build stays FAILED :(
        currentBuild.result = "UNSTABLE"
    } else {
        currentBuild.result = "FAILED"
        step([$class: 'StashNotifier'])   
    }
```

**Comment by scaytrase** [comment]
`NOT_BUILT` is already supported thanks to @aaronjwood at #116 (available with `1.11`). It's just does nothing at this state. Disable `INPROGRESS` notification if you not want to show it permanently.

Also since `1.11` (also #116) `UNSTABLE` build should go to the `SUCCESS` branch resulting in green build.

As for `ABORTED` it is not handled now, and I'm not sure that post-build steps are executed at this state. For me `ABORTED` should be equal to `NOT_BUILD` state (in terms of notifying stash)

> `step([$class: 'StashNotifier', buildResult: null])`

Is not really possible as there is no way to wipe certain build from stash commit. There is no DELETE method, nor the possibility to unset the state

https://developer.atlassian.com/static/rest/stash/latest/stash-build-integration-rest.html#resources

```
Supported values for the state are SUCCESSFUL, FAILED and INPROGRESS.
```

**Comment by philbert** [comment]
Oh Atlassian... Yes you're right there no DELETE method... not even an undocumented one...

But anyways, the point is still that tightly binding the jenkins build state to the stash build state is a mistake. 

The UNSTABLE jenkins state clearly indicates why this is a problem. For @aaronjwood maybe it is ok for UNSTABLE to equal SUCCESSFUL, but not where I am working. That must indicate FAILED in order to prevent pull requests from being merged.

But I do not want to have to modify the jenkins build state in order to post a FAILURE to stash. If my jenkins job has failed due to test cases I want the build to remain that way. We have a large organisation that runs many builds, so identifying a FAILED build that the tools team may need to look at from UNSTABLE builds that is more likely the developers problem to fix is important.

**Comment by scaytrase** [comment]
The only option I see is to have a checkbox, describing whether to count `UNSTABLE` as `FAILED` or `SUCCESSFUL`

But IMO `UNSTABLE` is passing (`SUCCESSFUL`) build, which should take a bit more attention. Most plugins have the limits when to count the build `SUCCESS`, `UNSTABLE` and `FAILED` (i.e xUnit plugin has failed testes limits). If the code is not good enough to be merged, it shoud not pass (`FAILED`).

Also Jenkins terminology agrees here:
https://wiki.jenkins-ci.org/display/JENKINS/Terminology

> `Unstable build`:
> A build is unstable if it was built **successfully** and one or more publishers report it unstable. For example if the JUnit publisher is configured and a test fails then the build will be marked unstable.

So unstable build is the successful one.

**Comment by philbert** [comment]
A checkbox for the plugin configuration would probably be sufficient for our purposes.

I won't debate your opinion whether UNSTABLE should be interpreted as SUCCESSFUL or FAILED. The point is to recognise there are different opinions on this topic, which means there are different use cases that need to be supported. 

I would really appreciate this change so that we can continue to use the plugin.

**Comment by philbert** [comment]
I just verified that ```currentBuild.result == "UNSTABLE"``` actually posts FAILED to Stash in version 1.11 of the plugin.

This is desired behavior from our perspective, but your comments indicate this may be a bug.

If you decide to change this behavior could you please implement some means of user configuration that allow us to decide how Jenkins currentBuild.result codes should be mapped to Stash build codes?

Thanks.

**Comment by James-Dengel** [comment]
Hey Guys, I also noticed that UNSTABLE reports as failed, can this be configure by the user ?
