### ISSUE TITLE
the plugin does not work with Atlassian Bitbucket v4.8.3

### ISSUE THREAD

**Issue by braghome** [jenkinsci/stashnotifier-plugin#130]
we have upgraded the v4.8.3 stash version see that with the latest version of the stashnotifier-plugin  does not work anymore.

**Comment by scaytrase** [comment]
Could you provide some logs, plugin version, jenkins version, etc?

**Comment by desmondchen** [comment]
I have the same problem after upgrade to 4.9.1.

**Comment by tenerd** [comment]
Tested stashnotifierplugin version 1.11.0 with  Bitbucket Server 4.10.0
Works for me.

**Comment by James-Dengel** [comment]
Atlassian Bitbucket v4.8.3
Plugin version 1.11.4

working here

**Comment by scaytrase** [comment]
I've updated to the latest 4.11.1 bitbucket and it works OK
