### ISSUE TITLE
groovy.lang.MissingPropertyException: No such property: commit for class: groovy.lang.Binding

### ISSUE THREAD

**Issue by donnib** [jenkinsci/stashnotifier-plugin#131]
So i am trying to use the Stash notifier in a Multibranch workflow so i put this very simple code in the jenkinsfile but it fails with` groovy.lang.MissingPropertyException: No such property: commit for class: groovy.lang.Binding` , it can't find the `commit `parameter ? What am i doing wrong here ?
```
node ('mac'){
   stage('Get Code') { // for display purposes
        
		this.notifyStash('INPROGRESS')         // Notifies the Stash Instance of an INPROGRESS build
		

	}
}

def notifyStash(String state) {

    if('SUCCESS' == state || 'FAILED' == state) {
        currentBuild.result = state         // Set result of currentBuild !Important!
    }

    step([$class: 'StashNotifier',
          commitSha1: "$commit",            // jenkins parameter that resolves to commit's hash
          credentialsId: '	ff1fcfbb-0fde-48ca-81b3-6f7a0ba41234',
          disableInprogressNotification: false,
          ignoreUnverifiedSSLPeer: true,
          includeBuildNumberInKey: false,
          prependParentProjectKey: false,
          projectKey: '',
          stashServerBaseUrl: 'http://stash'])

	}
```

Jenkins : 2.7.4
Bitbucket Server: 4.8.0

**Comment by scaytrase** [comment]
The extended example from readme does not define the source of the `$commit` variable. You should define one by yourself, i.e from build vars, env, file content, exec output, whatether you want.

It is just example with all possible parameters of groovy notifier call

**Comment by donnib** [comment]
Ok thx, i found out how, for other that are interested here is the code 

```
env.GIT_COMMIT = sh(script: "git rev-parse HEAD", returnStdout: true).trim()
echo env.GIT_COMMIT
```
I would suggest to put that code in the example, people can always change it.

**Comment by scaytrase** [comment]
PR is welcome

**Comment by todor-kolev** [comment]
I am facing the same issue when I have my pipeline parameterised with Git tag but if I trigger it from another job without passing in a parameter for the git tag. I thought it should just pick up the default value but instead it blows off with 
```
groovy.lang.MissingPropertyException: No such property: tag for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
```

**Comment by Rajendraladkat1919** [comment]
I am facing below issue with pipeline script.

```
groovy.lang.MissingPropertyException: No such property: GIT_CREDS for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
```

**Comment by 2313060585** [comment]
there another way to pull the job off, hope it's helpful
`sh "<shell command> > commandResult"
result = readFile('commandResult').trim()`

**Comment by 2313060585** [comment]
there another way to pull the job off, hope it's helpful
`sh "<shell command> > commandResult"'
'result = readFile('commandResult').trim()`

**Comment by 2313060585** [comment]
there is another way to pull the job off, hope it's helpful
`sh "<shell command> > commandResult"
result = readFile('commandResult').trim()`
