### ISSUE TITLE
Sometimes builds finished with "Authentication failed"

### ISSUE THREAD

**Issue by golak** [jenkinsci/stashnotifier-plugin#132]
Jenkins 2.24
Stash Notifier 1.11.4
Atlassian Bitbucket Server v4.4.1

({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":"com.atlassian.bitbucket.auth.AuthenticationSystemException"}]})

Before used
Jenkins 2.21 and Stash Notifier 1.10.4, but results were the same

**Comment by golak** [comment]
One more thing
Last errors were in parallel builds

The first
> 
12:30:57 Failed to notify Stash for commit 2fd96119ea1fe3484a298c2de5bb83c32443d712 ({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":"com.atlassian.bitbucket.auth.AuthenticationSystemException"}]})

The second

>
12:30:57 Failed to notify Stash for commit 7f6ab49ee507a9bae77b6faf5e009322e86ff210 ({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":"com.atlassian.bitbucket.auth.AuthenticationSystemException"}]})

**Comment by scaytrase** [comment]
Could you inspect bitbucket' side logs for failed authentication attempts?

**Comment by golak** [comment]
Seems like bitbucket issue. Sorry

**Comment by andyperlitch** [comment]
@golak what was the issue with bitbucket?
