### ISSUE TITLE
 v1.11.4 not working with Atlassian bitbucket v4.5.2

### ISSUE THREAD

**Issue by YannickteK** [jenkinsci/stashnotifier-plugin#133]
Hi It seems the stash notifier stopped working with the mentioned versions of the plugin and bitbucket. We couldn't get it fixed, so downgraded the plugin. Is it possible to fix this?

 It crashes with the following stacktrace:

> Caught exception while notifying Stash with id b0d08013df47c9b41edfd9cfd7eccbce10b2d425
> javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>     at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
>     at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
>     at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
>     at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
>     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
>     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
>     at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
>     at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
>     at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
>     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
>     at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
>     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
>     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
>     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
>     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
>     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
>     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
>     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
>     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
>     at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:689)
>     at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:287)
>     at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:240)
>     at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:206)
>     at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
>     at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1067)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
>     at hudson.model.Run.execute(Run.java:1745)
>     at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
>     at hudson.model.ResourceController.execute(ResourceController.java:98)
>     at hudson.model.Executor.run(Executor.java:401)
> Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>     at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
>     at sun.security.validator.Validator.getInstance(Validator.java:179)
>     at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
>     at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
>     at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
>     at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
>     at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
>     at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
>     at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
>     at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
>     at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
>     at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
>     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
>     ... 27 more
> Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>     at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
>     at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
>     at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
>     at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
>     ... 39 more

Thx in advance!

**Comment by gruetter** [comment]
compare [this conversation on StackOverflow](http://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty)

**Comment by gruetter** [comment]
We have just discovered the same problem with our servers (4.0.4 (!) and 4.8.6). Checking whether it's indeed a server configuration problem or if stashNotifier needs to be updated.

**Comment by gruetter** [comment]
Ok, turns out the problem went away as soon as we upgraded Java from 1.7 to 1.8 on our Jenkins server. It now works fine both with Bitbuckt 4.0.4 and 4.8.6 on our end. Could this be the problem on your end as well, @YannickteK ?

**Comment by ernsheong** [comment]
Try to check the ignore SSL option in Notify Stash > Advanced configuration plugin
