### ISSUE TITLE
This plug-in no longer appears in the jenkins index.

### ISSUE THREAD

**Issue by chazzly** [jenkinsci/stashnotifier-plugin#137]
No clue why, but I'm not seeing it from any of my jenkins servers (various 2.x versions).

the new Jenkins plug-in index lists a bitbucket-build notifier, but obviously not the same thing.

**Comment by scaytrase** [comment]
Well, actually I can find it here

https://updates.jenkins-ci.org/stable/update-center.json

**Comment by chazzly** [comment]
You are correct, interesting.  Unfortunately, however, it does not appear in the 'current' listing (which I believe is what gets referenced) HERE:
https://updates.jenkins-ci.org/current/update-center.json

or when you search here: 
https://wiki.jenkins-ci.org/dosearchsite.action?queryString=stashNotifier

or if you do a search here:
https://plugins.jenkins.io/

If I'm missing something, so be it, but I'm not able to install the plug-in because Jenkins can't find it.

**Comment by S3NS4Ti0N** [comment]
Any update on this ?

Still not be able to install this plugin.

Also, all links on the Wiki (https://wiki.jenkins-ci.org/display/JENKINS/StashNotifier+Plugin) for this plugin end in a 404

**Comment by scaytrase** [comment]
Looks bad. I'll try to find out why it happens.

Btw, You can always grab the ***.hpi** file to install from `releases` page here https://github.com/jenkinsci/stashnotifier-plugin/releases

**Comment by albertvipe** [comment]
Any update about this issue ?

**Comment by scaytrase** [comment]
@albertvipe no info yet, you can install the plugin manually from releases page

**Comment by lxkm** [comment]
@scaytrase Hey, quick check-in to see if there's been any progress on this...?

My team is setting up a new instance and we'll use the download version for now, but would much prefer tracking it in the stable releases if possible :)

**Comment by scaytrase** [comment]
@lxkm I'll try to submit stub release this weakend to overcome this problem

**Comment by lxkm** [comment]
Awesome! And thanks for the quick reply :)

**Comment by scaytrase** [comment]
I did two releases, [1.11.5 with old plugin URL](https://wiki.jenkins-ci.org/display/JENKINS/StashNotifier+Plugin) and [1.11.6 with new plugin URL](https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+(Stash)+Notifier+Plugin). tell me, which comes next

**Comment by scaytrase** [comment]
stashNotifier:1.11.6 is available on the plugins page
