### ISSUE TITLE
[question] How to overwrite build description coming from Jenkins

### ISSUE THREAD

**Issue by bingshiao** [jenkinsci/stashnotifier-plugin#141]
My jenkins build description has html tags, Stash Notifier takes the tags string and post to build status REST api of Bitbucket, which does not render html tags build status popup dialog. Is there a way to overwrite the build description coming from Jenkins build page or any workaround?

**Comment by scaytrase** [comment]
https://github.com/jenkinsci/stashnotifier-plugin/pull/126

**Comment by bingshiao** [comment]
Closing as it is duplicated with https://github.com/jenkinsci/stashnotifier-plugin/pull/126
