### ISSUE TITLE
JobDSL support and documentation example? 

### ISSUE THREAD

**Issue by lony** [jenkinsci/stashnotifier-plugin#144]
Looking at the [Job DSL documentation](https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.publisher.PublisherContext.stashNotifier) there seems to be an integration for this plugin. Sadly I could not get it to work and also could not find documentation for it.

1. Is it possible to add Job DSL support for this plugin if not existing?
2. Can the Readme.md (aka documentation) be enhanced with a example how to integrate this plugin with Job DSL?

Any help aka response would be appreciated.

Danke.

**Comment by scaytrase** [comment]
First time see this thing :) So I'm not sure it is really working now. Any improvements (feature, doc) welcome

**Comment by scaytrase** [comment]
It looks like that support was done long time ago on the DSL plugin side, not here. This plugin has evolved since there

**Comment by lony** [comment]
Could you point me to the initial change made in the DSL plugin? Maybe I can start from there.

**Comment by scaytrase** [comment]
Sorry, but can't. Just a suggestion, looking on the number of arguments documented

**Comment by eratolekov** [comment]
@lony 
Set jenkins global settings for StashNotifier (url, login, pswd, etc). Then use dsl
```
...
publishers {
        stashNotifier {
            keepRepeatedBuilds()
        }
    }
...
```

**Comment by lony** [comment]
@eratolekov Thank you! I tried your solution setting up the "default auth credentials" in the global Jenkins configuration and it worked!
Thats how I wanted it, thanks to both of you.

I would therefore close the issue.
