### ISSUE TITLE
Feature Request: Resolve failed build with same key

### ISSUE THREAD

**Issue by benwicks** [jenkinsci/stashnotifier-plugin#150]
I am using stash notifier to notify our BitBucket server of build statuses. I have the BitBucket repository configured to only allow merging PRs that have at least 1 passing build. This requirement also states that all builds on the PR need to pass in order to allow merging.

Sometimes, a build runs and fails. A subsequent build runs and succeeds after a necessary change is made. This should allow the PR to be merged. However, my BitBucket server sees multiple builds against the PR instead of a build that has been re-run and resolved.

Do you know of a good way around this? Could this be a feature in this plugin to notify stash with the same key when building against the same branch? Thanks. I found the following links in my research:

https://jira.atlassian.com/browse/BSERV-4869
https://developer.atlassian.com/bitbucket/server/docs/latest/how-tos/updating-build-status-for-commits.html

**Comment by scaytrase** [comment]
1. Changes usually result in new commit which leads to resetting the build list for PR
2. You can disable appending build number to the project key which results in overriding build result instead of appending it to the build list for certain job

**Comment by benwicks** [comment]
Your second point solved my issue. Thank you for the quick response!
