### ISSUE TITLE
How to configure on BitBucket (Stash) 

### ISSUE THREAD

**Issue by bweston92** [jenkinsci/stashnotifier-plugin#152]
So I have self hosted BitBucket (Stash) however how do I obtain these credentials?
![wtf](https://cloud.githubusercontent.com/assets/1764057/24444905/0076a1da-1460-11e7-8460-3dfd90bcacc6.png)

**Comment by scaytrase** [comment]
These are generic user credentials, i.e you can register a service user for this. Using trusted application is not supported and I don't even sure it is possible for rest api

**Comment by bweston92** [comment]
Ok so you're saying to use my own credentials on the status notifier or?

**Comment by scaytrase** [comment]
if this one suits you - yes. I do it for my own jenkins-bitbucket setup
