### ISSUE TITLE
Consider increasing severity of `found no commit info` message.

### ISSUE THREAD

**Issue by ftclausen** [jenkinsci/stashnotifier-plugin#156]
I was stuck for a while wondering why my build was not sending "in progress" notifications to stash but now I see it is because I was calling the Stash notifier step *before* checking out SCM. Maybe that `found no commit info` message can become an error or at least a warning? Also including some info about where the message is coming from might be convenient e.g. `stashnotifier-plugin: found no commit info`. It took me a while to realise that was actually a message from the stash notifier plugin.

**Comment by scaytrase** [comment]
Not a error for sure, as notifying is no an obligatory part of job.

Warning is considerable, but at the moment I cannot find any severity at all within the code, just `logger.println`

**Comment by ftclausen** [comment]
Thanks for ~~updating the README~~. I'll make a PR. You can close this ticket.
