### ISSUE TITLE
Mention in README to call StashNotifier after (git) checkout to properly set INPROGRESS status

### ISSUE THREAD

**Issue by bontscho** [jenkinsci/stashnotifier-plugin#157]
Hi there,

we integrated your plugin and noticed that the first step INPROGRESS was not set correctly. The Jenkins Log said "found no commit info".

After adding the `step([$class: 'StashNotifier'])` after `checkout()` has been called, the INPROGRESS state is set correctly.

Should the Readme contain this information?

Kind regards

**Comment by scaytrase** [comment]
Yes, README should reflect that commit info is acquired from build props by default which are set after checkout usually. Can you provide a PR?

relates to #156
