### ISSUE TITLE
Declarative Pipeline - Success and Failed not sent to Stash

### ISSUE THREAD

**Issue by gmercey** [jenkinsci/stashnotifier-plugin#160]
I'm calling StashNotifier in a declarative pipeline but it only send the _INPROGRESS_ status

```
pipeline {
  agent any
    stages {
      stage('Build') {
        steps {
          step([$class: 'StashNotifier'])
          echo 'Building.'
        }
      }
    }
    post {
      always {
        step([$class: 'StashNotifier'])
      }
  }
}
```

Is it a bug or do I not use the plugin properly?
Thanks

**Comment by pielu** [comment]
You need to setup currentBuild.result. I use shared libraries for that purpose. Otherwise it's null, hence the INPROGRESS.

**Comment by gmercey** [comment]
Thanks @pielu. Can you share an example of your implementation?

**Comment by scaytrase** [comment]
@gmercey readme has an example

**Comment by gmercey** [comment]
Ho I see! I didn't connect the dots. Thank you
