### ISSUE TITLE
Bad Request - Invalid URL

### ISSUE THREAD

**Issue by doogie2301** [jenkinsci/stashnotifier-plugin#164]
Plugin has been working fine until about week ago, possibly after updating other plugins.  Getting the following error now, regardless of the URL I specify in the config:

```
Failed to notify Stash for commit 0e9e8994243fd16519c7f10f228888c803624a9f (<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
)

```
There seems to be more logging in the source code for the release/1.x branch, is there any reason why that isn't in the build?  It might make this easier to debug.

**Comment by doogie2301** [comment]
It seems this only occurs when the URL is https, not http.  I tried the HTTP Request plugin using https and it works fine, though, so not sure what is different about this plugin.

**Comment by scaytrase** [comment]
@doogie2301 can you ensure that you can perform status update manually using HTTPS URL using the following API?

https://developer.atlassian.com/bitbucket/server/docs/latest/how-tos/updating-build-status-for-commits.html

**Comment by doogie2301** [comment]
Yes, the status updates work, as I have been doing that manually in the meantime.  I don't think it is actually even making a request to the server though, as I get the same result with any https URL, even if it doesn't exist.  It must be something about the http client that is rejecting it.

**Comment by doogie2301** [comment]
For now I have added a build step to use the HTTP Request plugin (which has no issue using the same https URL) to perform this task in place of the Stash Notifier plugin.
