### ISSUE TITLE
bitbucket incorrectly reports a finished build as 'in progress'

### ISSUE THREAD

**Issue by sdanieru** [jenkinsci/stashnotifier-plugin#166]
I have a build that finishes, but in Bitbucket the build is eternally reported as 'in progress'. I've rerun the job several times and it's always reported as 'in progress' on Bitbucket whether the job is running or finished.

In my Jenkinsfile, my build stage looks like this:
***
stage('build_app') {
    node ('docker') {
      step([$class: 'StashNotifier'])
      sh 'rm -rf dist'
      sh 'npm run build'
      step([$class: 'StashNotifier'])
    }
}
***

I'm surprised that it's not possible to specify more specific signals via the StashNotifier, e.g. 'startBuild' and 'endBuild'. Since it seems to be the same signal being sent, how does BitBucket know what the signal means?

**Comment by scaytrase** [comment]
hi, @sdanieru

you should set the current build result in order to send different state to the bitbucket. see readme for example. 
plugin does not know, whether your script is finished or not at the call point

**Comment by sdanieru** [comment]
got it working now, thanks!
