### ISSUE TITLE
({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":"com.atlassian.bitbucket.auth.IncorrectPasswordAuthenticationException"}]})

### ISSUE THREAD

**Issue by ankitgupta07** [jenkinsci/stashnotifier-plugin#168]
We are facing issue with stashnotifier plugin posting back response to Bitbucket. 

Error: ```({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":"com.atlassian.bitbucket.auth.IncorrectPasswordAuthenticationException"}]})```

Versions in use:
Atlassian Bitbucket v4.14.5
Jenkins 2.19.3
Stash Notifier plugin : 1.10.4

Issue is similar to https://github.com/jenkinsci/stashnotifier-plugin/issues/78 but since #97 fixed the issue, not sure why we are running into this issue. The version of plugin used is 1.10.4.

Further validated that we have the credentials specified in both global and job configuration. Since the issue with credentials present in job configuration was fixed in version 1.10.4, shouldn't this work even when credentials are present in both global and job configuration?

**Comment by scaytrase** [comment]
@ankitgupta07 can you ensure that you can perform JSON request with basic auth from Jenkins host to Bitbucket server?

**Comment by ankitgupta07** [comment]
@scaytrase So we run into this issue intermittently. When we run into this error, we need to unlock the account used for bitbucket. Once the account is unlocked by logging in and entering CAPTCHA, the notifications work again.

**Comment by scaytrase** [comment]
And what do you want from the plugin side? If the user account is locked - then performing request is not possible

**Comment by ankitgupta07** [comment]
We don't use the account for any other purpose. Let me re-phrase the problem.

- When we configured the job to notify stash/bitbucket, job was successful 
- All of a sudden, we got the error message posted in the issue title. After investigating found out that account was locked and we had to manually unlock it to make it work
- Then for another week or two, the notifications would work fine without any issues
- Again, we will run into similar issues with same symptoms.

I suspect that the issue is that when we run into the authentication issue, multiple login failures lead to account getting locked and hence unlocking the account helps. But the underlying problem is the error we are seeing in build logs - "({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":"com.atlassian.bitbucket.auth.IncorrectPasswordAuthenticationException"}]}) "

**Comment by scaytrase** [comment]
You should investigate the reasons of locking the user on the Bitbucket side first. I.e this can be caused by upstream auth provider (JIRA, AD, other) inaccessibility leading to auth failures and deactivating account
