### ISSUE TITLE
CredentialsId does not work

### ISSUE THREAD

**Issue by abialas** [jenkinsci/stashnotifier-plugin#169]
I am trying to use StashNotifier plugin in pipeline job. I am setting the correct credentialsId but unfortunatelly I get response from server:
"You are not permitted to access this resource"

User which is defined by this credentials has read repository permisions.

Adam

**Comment by scaytrase** [comment]
@abialas Obviously to **modify** the state of the commit build status you should have a kind of mutating permissions to the repository, so you can't modify the state of the build as soon as you can't modify the state of the repository. Try write or admin permissions first, then try to downgrade them as much as possible.

The official documentation says that user should have `LICENSED` permissions, but I think it is a bit incorrect

**Comment by abialas** [comment]
I cannot find the official documentation - can you give me a link please?
