### ISSUE TITLE
bug/fix-tls

### ISSUE THREAD

**Issue by gsapozhn** [jenkinsci/stashnotifier-plugin#170]
Hello,

I could not find PR #162 in any release tag. Is there a plan to merge this branch and release the plugin? Our Bitbucket is being upgraded to TLS 1.1+ and this fix will be needed to avoid the SSL handshake error on notifying.

Thank you!
Gleb Sapozhnikov

**Comment by scaytrase** [comment]
Wow, I've missed that PR somehow, I'll try to manage this as soon as I can. Thank you for pingback @gsapozhn
