### ISSUE TITLE
currentBuild.result = null in Declarative Pipeline

### ISSUE THREAD

**Issue by pongells** [jenkinsci/stashnotifier-plugin#171]
Looks like `currentBuild.result = 'SUCCESS'` and `currentBuild.result = null` are the same in Declarative Jenkins pipelines. 

However, stash will not notify correctly if `currentBuild.result = null` (which is default value for successful builds).

**Comment by scaytrase** [comment]
`null` value is treated as `INPROGESS` state unless you disable this option

https://github.com/jenkinsci/stashnotifier-plugin/blob/release/1.x/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java#L238

You should manually set `currentBuild.resut` in your pipe line, see the README

**Comment by pongells** [comment]
hey scaytrase, thanks for the quick reply 👍 

do you know if there is a 'nice' way to set the currentBuild.result in declarative pipelines? from what I understood the whole idea of using declarative vs. scripted is to hide that extra logic (build state is managed behind the scenes, and for some reason they decided NULL would mean SUCCESS).

only way I found is to add a script {} step.. not the nicest of things to be honest.

**Comment by scaytrase** [comment]
Not sure, that I agree with this whole idea. For me idea of pipelines is possibility to make complex builds with different ways of execution (conditions, branching, loops, delegating, etc), so you must control everything programmatically, so I don't think we should have easier way to set currentBuild.result.

**Comment by geranim0** [comment]
pongells is right and scaytrase is wrong

**Comment by anilsakr** [comment]
I had an issue even I manually setting the `currentBuild.result = 'SUCCESS'`
when I change this to below **Its working fine for me**
`currentBuild.result = hudson.model.Result.SUCCESS.toString()`

**Comment by melaronquillo** [comment]
> I had an issue even I manually setting the `currentBuild.result = 'SUCCESS'` when I change this to below **Its working fine for me** `currentBuild.result = hudson.model.Result.SUCCESS.toString()`

This was a lifesaver. Thanks
