### ISSUE TITLE
Shared Pipeline Libraries: suppress status updates for shared repository

### ISSUE THREAD

**Issue by thomasstache** [jenkinsci/stashnotifier-plugin#173]
With Jenkins pipeline becoming the preferred/recommended way to define jobs and placing common code in a shared (Git) repository, StashNotifier attributes build status also to the pipeline repository. So a compile or test error _in any app job_ would be reported on the Jenkins Shared Library commit.

So to be clear: We don't need to notify for more (multiple) commits, but less!

I would have seen this as similar to #87, but that has been closed in January 2016 (although I don't see the relation to #90 that led to that)!

Defining the whole pipeline in a shared repository:
https://jenkins.io/doc/book/pipeline/shared-libraries/#defining-declarative-pipelines

**Comment by scaytrase** [comment]
You can try to define commit SHA-1 with token macro instead of default env GIT_SHA

**Comment by thomasstache** [comment]
I've read something about Pipeline Compatibility in #145 - would that be required? Do you have plans to ship a new release containing the improvements of the last 9 months of work?

Thanks for the quick reply!

**Comment by scaytrase** [comment]
Yes, I have plans to ship new release soon

**Comment by scaytrase** [comment]
@thomasstache I've released 1.12 with all the latest PRs. Feel free to check it

**Comment by thomasstache** [comment]
Why are you so eager to close issues?

> You can try to define commit SHA-1 with token macro instead of default env GIT_SHA

Can you give a tip what you mean, how to do this?

**Comment by scaytrase** [comment]
Stashnotifier accepts SHA-1 hash as one of the step arguments. You can pass certain commit sha-1 to be notified.

You can try to find the full step argument list in the README

**Comment by Wilfred** [comment]
Aha, that's really helpful. Here's an example I've written based on the above discussion:

```groovy
node('node-label-here') {
    try {
        stage("Checkout") {
            def checkoutVars = checkout scm

            // https://issues.jenkins-ci.org/browse/JENKINS-26100
            def gitCommit = checkoutVars["GIT_COMMIT"]
        }

        // Notify that the build started.
        step([$class: 'StashNotifier', commitSha1: gitCommit])

        stage("Tests") {
            // ...
        }

        currentBuild.result = 'SUCCESS'
    } catch (e) {
        currentBuild.result = 'FAILURE'
        throw e
    } finally {
        step([$class: 'StashNotifier', commitSha1: gitCommit])
    }
}
```

**Comment by scaytrase** [comment]
@Wilfred I'm not a groovy guru, but from the basic developer PoV it's better to move checkout stage out of the try..catch block, since you can get non-initialized `gitCommit` on checkout failure exception processing

**Comment by riy** [comment]
This is an issue that I was fighting with as well. When a shared library is imported in my `Jenkinsfile` its commit ID will also be used by the StashNotifier plugin. I was able to find a solution to prevent this from happening.

This is what my `Jenkinsfile` now looks like:

```groovy
[...]
node {
  stage('checkout') {
    checkout scm
  }

  reportBuildStatus('my-repository-name', {
    withEnv(["JAVA_HOME=${tool 'jdk-11.0.2'}"]) {
      stage('clean') {
        sh "${gradle} clean"
      }

      stage('build') {
        sh "${gradle} build"
      }
      [...]
    }
  })
}

[...]

def reportBuildStatus(String repositoryUrl, Closure x) {
  def url = sh(returnStdout: true, script: 'git config remote.origin.url').trim()
  def gitCommit = sh(returnStdout: true, script: 'git log --format="%H" -n 1').trim()
  if (url.contains(repositoryUrl)) {
    reportBuildStatusResult(gitCommit, 'INPROGRESS')
  }

  try {
    x()
    reportBuildStatusResult(gitCommit, 'SUCCESS')
  } catch(err) {
    reportBuildStatusResult(gitCommit, 'FAILED')
    throw err
  }
}

private def reportBuildStatusResult(String gitCommit, String result) {
  def originalCurrentBuildResult  = currentBuild.result
  try {
  currentBuild.result = result
  step([$class: 'StashNotifier', buildStatus: result, commitSha1: gitCommit])
  } finally {
  currentBuild.rawBuild.@result = originalCurrentBuildResult
  }
}
```

There are two important tidbits here:
1. The `checkout scm` needs to happen before the StashNotifier is called.
2. The `my-repository-url` needs to contain the name of the project you're building, contained in the repository url. Example: `https://github.com/myname/my-repository-name.git`. This ensure the commit happens for the currently building repository and its commit ID only.

The remaining code should be pretty much self-explanatory.

HTH!
