### ISSUE TITLE
Error "Please specify a valid url"

### ISSUE THREAD

**Issue by cnacu6o** [jenkinsci/stashnotifier-plugin#182]
Hi!
I have this config
![image](https://user-images.githubusercontent.com/1105567/33348468-9a8beaca-d4a7-11e7-99cf-da4d81aa7749.png)

and this error:

`First time build. Skipping changelog.
Notifying Stash at "http://localhost:7990/bitbucket"
Failed to notify Stash for commit 724321093de2b4c2408dc42726578e594c7400a2 ({"errors":[{"context":null,"message":"Please specify a valid url","exceptionName":null}]})
Notifying Stash at "http://localhost:7990/bitbucket"
Failed to notify Stash for commit 65ca7111ceadbce4849b3577a712c4071686ffee ({"errors":[{"context":null,"message":"Please specify a valid url","exceptionName":null}]})
Notifying Stash at "http://localhost:7990/bitbucket"
Failed to notify Stash for commit 724321093de2b4c2408dc42726578e594c7400a2 ({"errors":[{"context":null,"message":"Please specify a valid url","exceptionName":null}]})
Notifying Stash at "http://localhost:7990/bitbucket"
Failed to notify Stash for commit 65ca7111ceadbce4849b3577a712c4071686ffee ({"errors":[{"context":null,"message":"Please specify a valid url","exceptionName":null}]})`

Curl works fine

`curl --user **:** -H "Content-Type: application/json" -X POST http://localhost:7990/bitbucket/rest/build-status/1.0/commits/724321093de2b4c2408dc42726578e594c7400a2 -d @build0.json`

**Comment by scaytrase** [comment]
@cnacu6o are your jenkins and bitbucket on the same host?

**Comment by cnacu6o** [comment]
@scaytrase yes. Same host. Jenkins addres **http://localhost:8081**

**Comment by scaytrase** [comment]
haven't you specified any invalid URL on global configuration page?

**Comment by cnacu6o** [comment]
I specified url **http://localhost:7990/bitbucket** and leave blank. Same result.

**Comment by scaytrase** [comment]
Do you have jenkins base url properly configured (in jenkins global config)? Looks like that build URL, which is sent alongside the build status is not accepted on bitbucket side

**Comment by cnacu6o** [comment]
forgot **http://** in jenkins global url-config. Thank you!
