### ISSUE TITLE
Cannot use custom SHA value for INPROGRESS status

### ISSUE THREAD

**Issue by vassilevsky** [jenkinsci/stashnotifier-plugin#187]
Hello 🙃

I set up Jenkins jobs to build Stash pull requests.

Stash creates "hidden" branches for each pull request:
* refs/pull-requests/123/from — points to the branch from which the PR is created
* refs/pull-requests/123/merge — (created only if there are no merge conflicts) merge result

They aren't really hidden. I can see them with `git ls-remote | grep pull`.

I set up Jenkins in such a way that it builds all merge branches. I think that this is safer. It could be that the source branch is built successfully, but the merge result is not.

The problem is that any build status posted to the SHA of the merge branch is not visible in Stash UI.

So I do a little trick to post the status to the source SHA instead.

```shell
PR_ID=$(echo $GIT_BRANCH | cut -d / -f 3)
FROM_BRANCH=origin/pull-requests/$PR_ID/from
FROM_SHA=$(git rev-parse $FROM_BRANCH)
```

Then I insert `$FROM_SHA` into the *Commit SHA-1* field of this plugin.

It works after the build! I actually see the statuses in Stash.

But it does not work before the build, for the INPROGRESS status. I get the "Unable to expand $FROM_SHA macro" error. Because the script hasn't yet run at that point.

I tried the EnvInject plugin but it also runs after the INPROGRESS status is posted.

What can I do?

**Comment by scaytrase** [comment]
Sorry for me, I somehow missed this issue in my feed. Better option is to use pipelines for now, you can control the order of plugins there.

Alson there is a plugin for bitbucket which indicates the build status of the merge commit, so you do not have to manipulate the SHA's, merge commit is marked separately via native GIT_SHA

I thinik this can be closed, feel free to reopen if you still need help

**Comment by vassilevsky** [comment]
Bitbucket Branch Source plugin solves this problem. We’re using it now. Thanks :)

**Comment by scaytrase** [comment]
Me too, actually ( with pretty blue ocean
