### ISSUE TITLE
The wrong icon for Build Status is shown in Bitbucket

### ISSUE THREAD

**Issue by rudyde** [jenkinsci/stashnotifier-plugin#194]
I've problem if build is succesful it's still showing  the icon that build is in progress. But if build is failed then it show the correct icon (the red one).

I'm using Bitbucket Server 5.8.1,  Stash Notifier Plugin 1.13 and Jenkins 2.104

would really appreciate if you can help me to solve this.

 

Thanks in advanced

**Comment by johanrydstrom** [comment]
I've experienced that a build "stays running" according to Stash/BitBucket, even though the StashNotifier has been called in the end of the process. I'm using a declarative Jenkinsfile, with something like this as post steps:
```
pipeline {
...
   post {
      always {
         step([$class: "StashNotifier"])
      }
   }
}
```
but Stash still says "Build in progress".

Could the problem be that `buildResult == null`, i.e. that we end up on this line?
https://github.com/jenkinsci/stashnotifier-plugin/blob/1e63569edcadec57d19503b3f5c997794d102dec/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java#L260

**Comment by scaytrase** [comment]
According to readme you can use the following format
```groovy
    post { 
        always { 
            script {
                currentBuild.result = currentBuild.result ?: 'SUCCESS'
                notifyBitbucket()
            }
        }
    }
```
