### ISSUE TITLE
Notify submodule repositories

### ISSUE THREAD

**Issue by Hickstone** [jenkinsci/stashnotifier-plugin#195]
I want to notify every repository that was integrated via git submodules.
Is this possible?
I only get a notification for the parent repository.

**Comment by scaytrase** [comment]
@Hickstone for submodules you have to manually iterater them and use notification command, since multiple repositories are not allowed to be notified at once at the moment

**Comment by scaytrase** [comment]
And it's possible in pipeline only

https://github.com/jenkinsci/stashnotifier-plugin#note-on-pipeline-plugin-usage
