### ISSUE TITLE
Comment on PR

### ISSUE THREAD

**Issue by OneMoreByte** [jenkinsci/stashnotifier-plugin#196]
I want a more verbose description of a failure when my pull requests are built. Is there a way/are you planning or willing to have an ability to do that?

**Comment by scaytrase** [comment]
Currently the build description is set to the build status comment, so you can utilize it for your purposes

**Comment by OneMoreByte** [comment]
Would the option to have stashnotifier also send a comment to a commit or PR be something that you would be OK having included in this plugin?

**Comment by scaytrase** [comment]
Currently there is neither excplicit processing of pull requests in this plugin nor plans to implement it. I think you are looking for something like https://github.com/jenkinsci/stash-pullrequest-builder-plugin

**Comment by OneMoreByte** [comment]
Oh cool. Thanks!
