### ISSUE TITLE
Notification URL

### ISSUE THREAD

**Issue by qianmuxi** [jenkinsci/stashnotifier-plugin#198]
Hello:

this plugin Notification URL is blue ocean，but I do not want this.How can I set classic one?

**Comment by scaytrase** [comment]
Plugin uses URL Api provided by Jenkins and it does not generate neither classic nor blue ocean url, but an intermediate URL which is being redirected according to Jenkins settings (to either classic or blue ocean). Unfortunately I do know where this API is configured from within Jenkins settings

**Comment by chpro** [comment]
It is possible to set the used provider via property or environment variable. The provider you should use is `org.jenkinsci.plugins.displayurlapi.ClassicDisplayURLProvider`.

See https://github.com/jenkinsci/display-url-api-plugin/blob/master/src/main/java/org/jenkinsci/plugins/displayurlapi/DisplayURLProvider.java#L158-L159

Hence, under debian you can set the property in /etc/default/jenkins with 
```
JAVA_ARGS="-Djenkins.displayurl.provider=org.jenkinsci.plugins.displayurlapi.ClassicDisplayURLProvider"
```
