### ISSUE TITLE
Missing default value in post directives

### ISSUE THREAD

**Issue by benjah1** [jenkinsci/stashnotifier-plugin#203]
I am using jenkins library. The func works is `steps {}`, but throw error in `post {}`.

In Jenkins library,
```
...
        post {
            always {
                notifyBitbucket commitSha1: "${env.GIT_COMMIT}"
            }
        }
...
```

And error, 
```
hudson.remoting.ProxyException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/data/jenkins_master/jobs/qa/jobs/common-web-starter/branches/RPD-7797/builds/1/libs/my-ci/vars/pipelineMsJavaLib.groovy: 85: Missing required parameter: "stashServerBaseUrl" @ line 85, column 17.
                   notifyBitbucket commitSha1: "${env.GIT_COMMIT}"
                   ^

/data/jenkins_master/jobs/qa/jobs/common-web-starter/branches/RPD-7797/builds/1/libs/my-ci/vars/pipelineMsJavaLib.groovy: 85: Missing required parameter: "credentialsId" @ line 85, column 17.
                   notifyBitbucket commitSha1: "${env.GIT_COMMIT}"
                   ^
....
```

Jenkins version: 2.138
Pipeline: 2.5
Pipeline: Shared Groovy Libraries: 2.10
Stash Notifier: 1.13

**Comment by scaytrase** [comment]
I don't something could be fixed on plugin side, since there is no knowledge of neither `post` nor `step` clause. If different clauses instantiate plugin differently - I think there is problem with pipeline interpreter itself

**Comment by benjah1** [comment]
@scaytrase My thought is the same as yours. 

After more reading, 
https://stackoverflow.com/questions/44531003/how-to-use-post-steps-with-jenkins-pipeline-on-multiple-agents
https://github.com/jenkinsci/pipeline-model-definition-plugin/wiki/Controlling-your-build-environment#3-i-like-to-drive-stick-get-out-of-my-way

This happens because I am using one the practice. There are two way to fix this,
* in pipeline, instead of agent none, specify a agent.
* in post, use node('label').

**Comment by scaytrase** [comment]
@benjah1 would you mind to open PR to mention this in readme with example of correct usage?
