### ISSUE TITLE
Question about posting comments

### ISSUE THREAD

**Issue by bfaure** [jenkinsci/stashnotifier-plugin#204]
Is there a way to edit the comment portion of the build status? So, for instance, so I can pass some information back to Bitbucket (stash) such as number of failed tests, linting results, etc.

**Comment by scaytrase** [comment]
@bfaure Build description is currently passed as the comment portion

**Comment by bfaure** [comment]
Thank you, not to be a bother but is there a way of setting the comment portion through the UI? In the post build action (in the pic below) I don't see anywhere to input that.
![image](https://user-images.githubusercontent.com/10341772/45440370-0f1b7580-b68a-11e8-86a0-17bccff030c8.png)

**Comment by scaytrase** [comment]
You can use plugins like Project Description Setter Plugin

**Comment by bfaure** [comment]
Great, thanks so much.
