### ISSUE TITLE
Make job optional in notification url

### ISSUE THREAD

**Issue by bmagistro** [jenkinsci/stashnotifier-plugin#206]
Currently the job id is included in the stash/bitbucket notification url `http://stash-server/job/<project>/job/<branch>/<job id>`.  This takes you to job specific view.  At the global level it would be nice to be able to make `job id` optional so that you can be taken to the branch summary page.

**Comment by scaytrase** [comment]
I'm not really sure this is good idea since people expect build state lead to the build view to see it's logs in case of failure or something. Pointing people to job feed would confuse people, especially in case of viewing old builds when build they try to inspect is not the last in the build feed

**Comment by bmagistro** [comment]
I completely understand where you are coming from and certainly can see the value in linking to a specific build.  This is the main reason I think it should be a user configurable item.

For the instance we are using, it only keeps the last n (~10 or so) builds so even if it does link to a specific build it is possible the link will have aged off and be dead.  This is also likely specific to our environment and what we have needed so far but we tend to only use the logs on recent builds.

If you don't mind can we leave this open for a bit and see what others might think?  If it seems to have no interest in say a couple months I am okay with marking it closed as "won't change/add".  If we get time and decide we really want to pursue this would you be open to a pr with this change?

**Comment by scaytrase** [comment]
We can leave this open for sure.

But I still think that dead link management is something what could be handled on jenkins side itself. You could get dead links for many reasons, i.e renaming or moving job to another collection, getting 404 on build link. Handling all these cases within every plugin side which utilize build links would be weird

**Comment by scaytrase** [comment]
I hope this is covered by #303
