### ISSUE TITLE
getBuildDescription builds incorrect Jenkins URL in case of specific Jenkins configs

### ISSUE THREAD

**Issue by BalintSzigeti** [jenkinsci/stashnotifier-plugin#207]
in 1.14 version the following part is missing from the jobs' config.xml file 
```
<globalConfig>
      <globalConfig/>
        <adminAddress>Mr. Jenkins <jenkins@example.com></adminAddress>
        <jenkinsUrl>https://example.com/</jenkinsUrl>	
 </globalConfig>
```
Because this is not **in** the job's config.xml the plugin doesn't collect this data from jenkins instance.

This method doesn't work properly in StashNotifier.java#285:
```
 private String getRootUrl() {
        Jenkins instance = Jenkins.getInstance();

        if (null == instance) {
            return globalConfig.getUrl();
        }

        return (instance.getRootUrl() != null) ? instance.getRootUrl() : globalConfig.getUrl();
    }
```

**Comment by scaytrase** [comment]
@BalintSzigeti which version are you upgrading from?

**Comment by BalintSzigeti** [comment]
1.13

**Comment by scaytrase** [comment]
There is no specific changes on this code between 1.13 and 1.14

https://github.com/jenkinsci/stashnotifier-plugin/compare/1.13...1.14

**Comment by BalintSzigeti** [comment]
well, than I don't have clue. I upgraded the plugins on 2.116 to latest then upgrade Jenkins itself from 2.116 to 2.144.
Then the jobconfighistory plugin shows the above mention section is missing from jobs' config.xml and the messages in Stash(bitbucket) do not contain the link. 
```
[BuildFinished unit-pr] 7df0d37173df010bf363e59b35248beba14f8148 into 1e4371267e0e579391b441556a436600fa8fd4c3

[BUILD SUCCESS]( PLEASE SET JENKINS ROOT URL FROM GLOBAL CONFIGURATION job/junit-pr/2058/) - Build #2058 which took 7 min 2 sec
```
and the BUILD SUCCESS string is not link anymore because the root url is missing form the link.

**Comment by BalintSzigeti** [comment]
is there anything that I can do to collect more data about this issue which would help you?

**Comment by BalintSzigeti** [comment]
is there a way to allow the users to specify the 'global' config AKA override it at jobs level? As I mentioned, this part was in the config.xml and it is gone.

**Comment by scaytrase** [comment]
Yes, you can define bitbucket url on jenkins` level and override it for specific jobs.

Can you ensure that Jenkins has it's `Jenkins Location > Jenkins URL`  still configured on `/configure` page? I'm not sure is it a problem of plugin or somewhere in the jenkins

**Comment by BalintSzigeti** [comment]
I think you misunderstood the issue. The bitbucket URL is properly set otherwise the message wouldn't appear on stash webUI. The problem is the revers direction. The stashnotifier plugin tries to put the job's url into the message and that URL building doesn't work. The
`<server url>/configure -> Jenkins Location `is set and the `Stash Notifier section` is properly filled in.

**Comment by BalintSzigeti** [comment]
I've just upgraded Jenkins to 2.146 but the issue is still there.

**Comment by scaytrase** [comment]
Ok, I've got you. Not sure it's a plugin problem, but looks valid anyway

**Comment by BalintSzigeti** [comment]
could I do anything to speed up the fixing? debug, test, logs?

**Comment by scaytrase** [comment]
PR is always welcome as most efficient fixing speedup

**Comment by nicksanders** [comment]
I updated Jenkins to 2.148 and at the same time updated to 1.14 and saw the same issue

I downgraded to 1.13 but the issue still occurred

I checked the job config before and after saving a job without changing anything

BEFORE:

      <globalConfig>
        <adminAddress>support@example.com</adminAddress>
        <jenkinsUrl>http://192.168.1.253:8080/</jenkinsUrl>
      </globalConfig>

AFTER:

     <globalConfig/>

**Comment by BalintSzigeti** [comment]
I presume something is changed in core jenkins otherwise it should work according to stashnotify SRC.

**Comment by scaytrase** [comment]
@BalintSzigeti can you report it to the Jenkins core? I'll keep this open for case of plugin update is required

**Comment by BalintSzigeti** [comment]
I'm not sure of my idea. Plus if I report it I would be a proxy.

**Comment by scaytrase** [comment]
I'll be worse proxy since I do not have this bug reproduced
