### ISSUE TITLE
Unstable builds are marked as FAILED in Bitbucket

### ISSUE THREAD

**Issue by papanito** [jenkinsci/stashnotifier-plugin#208]
Currently unstable builds in Jenkins are marked as failed in Bitbucket. 
![image](https://user-images.githubusercontent.com/15034009/47198678-0a736c80-d36e-11e8-8bdf-dcdcf8b3109b.png)

![image](https://user-images.githubusercontent.com/15034009/47198589-6a1d4800-d36d-11e8-91a4-e74ee2b88eed.png)

The stash-notifier plugin has the respective checkbox "Consider UNSTABLE builds as SUCCESS notification" ticked
![image](https://user-images.githubusercontent.com/15034009/47198653-df891880-d36d-11e8-8486-1560baf2226e.png)

Environment:

- Jenkins 2.138.1
- Stash Notifier Plugin 1.14
- Bitbucket Server 5.9.0

**Comment by scaytrase** [comment]
IIUC this is pipeline and screenshot it from global settings. Could you please provde the pipeline script itself?

**Comment by papanito** [comment]
We don't call `notifyBitbucket()` directly but rather use the [Webhook to Jenkins for Bitbucket](https://marketplace.atlassian.com/apps/1211284/webhook-to-jenkins-for-bitbucket?hosting=server&tab=overview). According to the vendor the issue I am facing has noting to do with their plugin however

> I believe it happens within scope of Stash Notifier Plugin (https://plugins.jenkins.io/stashNotifier)
> Our plugin doesn't do anything on Jenkins side

So I am a bit puzzled whats going on and where does the issue come from

**Comment by scaytrase** [comment]
Well, another option - you've used bitbucket branches provider plugin, which utilizes it's own notifier

**Comment by papanito** [comment]
Good hin thanks - yes we use "Bitbucket Branch Source Plugin".

**Comment by papanito** [comment]
Opened a bug report at the correct place: https://issues.jenkins-ci.org/browse/JENKINS-54157

**Comment by scaytrase** [comment]
Good. I'll close this then. Feel free to return back and reopen it if needed
