### ISSUE TITLE
Disable INProgress notification option in UI doesn't work - Still get a PR comments that Jenkins PR triggered job has started

### ISSUE THREAD

**Issue by maxwellmckinnon** [jenkinsci/stashnotifier-plugin#215]
In addition, a nice to have for this item would be getting the INProgress build column visual enabled independently.

**Comment by maxwellmckinnon** [comment]
Err. This behavior may be due to the Stash pullrequest builder plugin actually. I'll make a bug there too.

**Comment by scaytrase** [comment]
@maxwellmckinnon did you find out which one causes the issue?
