### ISSUE TITLE
Not working with Bitbucket Server "found no commit info"

### ISSUE THREAD

**Issue by jsdevel** [jenkinsci/stashnotifier-plugin#219]
Here's my setup:

* Jenkins 2.163
* Bitbucket Server 5.8.1
* Stash Notifier 1.15

I see the message "found no commit info" before and after my build.

**Comment by jsdevel** [comment]
Seems it's related to the git plugin: https://issues.jenkins-ci.org/browse/JENKINS-55939?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27git-plugin%27

lastBuildRevision is broken in GitPlugin 4.0.0-rc

**Comment by jsdevel** [comment]
Downgraded GitPlugin to 3.9.1 and now it's working great!

**Comment by scaytrase** [comment]
Not sure but you can try HPI from #218

https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fstashnotifier-plugin/detail/PR-218/1/artifacts

**Comment by kousik93** [comment]
I can confirm this breaks in Git Plugin Version 4.0.0-rc

**Comment by scaytrase** [comment]
reverted in https://github.com/jenkinsci/stashnotifier-plugin/releases/tag/1.17
