### ISSUE TITLE
Failed to notify Stash for commit 

### ISSUE THREAD

**Issue by sgcsekar** [jenkinsci/stashnotifier-plugin#224]
We are using pipeline job and build job has been completed successfully but failed to notify  back to Bitbucket.
we are getting below logs from Jenkins console. Could you please advice that what could be went wrong here?

Failed to notify Stash for commit XXXX ({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":"com.atlassian.bitbucket.auth.IncorrectPasswordAuthenticationException"}]})

**Comment by scaytrase** [comment]
Well, looks something wrong happened during notification request according to auth (i.e auth provider for bitbucket was unreachable). Does this repeat each time? Did you check the credentials?

**Comment by sgcsekar** [comment]
credentials are fine, when we re-trigger it, Jenkins can notify stash.

**Comment by scaytrase** [comment]
So it was one-time problem?
