### ISSUE TITLE
False negative build failure for last successful SHA is sent to Stash upon clone failure

### ISSUE THREAD

**Issue by srazzaque** [jenkinsci/stashnotifier-plugin#23]
# Background

We're using Stash and have a "minimum successful build" requirement on Pull Requests. We also have a build set up in Jenkins as our "authoritative build" upon which we base our acceptance of the pull request.

This build has a parameterized repository URL, and everyone is able to use it, point it to point to their own forks and build their branches.

Problem is, sometimes people open up a pull request, get a successful build, only to find later that their build has been marked unsuccessful due to this bug.

# Scenario & Reproduction Steps

* Sue makes commit with SHA 'abc123' on her fork to branch "sues-branch"
* Sue kicks off the build and gets a successful build
* This is correctly reported to Stash as a success against 'abc123'
* Jim makes commit with SHA 'def456' onto his fork to branch "jims-branch"
* Jim then attempts to kick off the build, but forgets to change the repository URL to his fork (it has some other default)
* Build fails because branch 'jims-branch' did not exist on the main repository

Expected result:
* No notification sent to stash

Actual result:
* Notification is sent to stash with *sue's commit SHA of 'abc123'* (i.e. last successful build). This marks Sue's pull request as failing (i.e. a false negative).

# Version details

Jenkins version: 1.509.4
Stash notifier plugin version: 1.5

**Comment by scaytrase** [comment]
Isn't `workspace cleanup before build` solving this problem? as far as I understend this will erase git commit from workspace too, so no commit should be stored at checkout moment
