### ISSUE TITLE
Hangs at "Notifying Stash at ..."

### ISSUE THREAD

**Issue by andham** [jenkinsci/stashnotifier-plugin#230]
In our environment we're sometimes having some network issues with our Bitbucket Server instance. This seems to cause "Notify Stash Instance" post-build actions to hang. My guess is that there is a missing timeout.
The result is that the build hangs for ever and it is not even possible to cancel from the Jenkins UI.

What we see in the build job console log is:
Notifying Stash at "https://bitbucket.foo.bar"
and then a spinning wheel...

Environment:
Jenkins LTS 2.150.3 on RHEL 7 and openJDK 1.8.0
Stash Notifier plugin v1.17

**Comment by scaytrase** [comment]
Looks like we tried to fix it some time ago

https://github.com/jenkinsci/stashnotifier-plugin/pull/135/files

**Comment by andham** [comment]
It doesn't seem to be enough in my case. Possibly connection timeout needs to be set as well.
