### ISSUE TITLE
Allow to tell which for repositories (and branches?) to notify

### ISSUE THREAD

**Issue by orgi** [jenkinsci/stashnotifier-plugin#235]
For bigger pipelines it's quite common that more than one repository will be cloned.
However a test job usually targets one specific repository while the others shall not be marked as pass / fail as this will result in unrelated commits being marked as passed, failed or in progress.

Not sure what would be the best way to implement this. Maybe some additional parameter taking the url to the repository?

**Comment by scaytrase** [comment]
There is no way to notify branch, there is only commit sha1 which is being notified. You can see it in the API docs mentioned in README. For other cases it duplicates #90 and #61

**Comment by orgi** [comment]
I see, thanks for the links. Just reading the title I would not have thought that they would be related.
