### ISSUE TITLE
Access key should be used instead of user credentials

### ISSUE THREAD

**Issue by OndraM** [jenkinsci/stashnotifier-plugin#24]
Since Stash 2.9 it is possible to user Access keys instead of user credentials:
https://blogs.atlassian.com/2013/11/stash-2-9-manage-branch-build-and-repository-access-with-ease/#Stash2.9BlogPost-Accesskeys

These should be used so Stash user password won't have to be stored in the Jenkins plugin configuration.

**Comment by ashnazg** [comment]
Is it possible to reconsider this now?  I can't determine for sure if Stash has enabled an access key method that doesn't require OAuth yet.  I'm trying to put together a patch, but I'm stuck on what to use instead of UsernamePasswordCredentials.
