### ISSUE TITLE
Missing required parameter: "buildName"

### ISSUE THREAD

**Issue by adrian-at-dmi** [jenkinsci/stashnotifier-plugin#245]
Just updated to v1.20 and received build errors with the following message:
```
WorkflowScript: 36: Missing required parameter: "buildName" @ line 36, column 5.
   				notifyBitbucket commitSha1: "${env.GIT_COMMIT}", considerUnstableAsSuccess: false, credentialsId: '<some-guid>', disableInprogressNotification: false, ignoreUnverifiedSSLPeer: false, includeBuildNumberInKey: true, prependParentProjectKey: false, projectKey: '', stashServerBaseUrl: '<some-url-to-bitbuckt-server>'
```

Looks like #241 introduced an backwards-incompatible change even though the issue suggests that the "buildName" parameter should be optional. The parameter also does not appear in the snippet generator which makes it hard to know what it does, how it works and that it exists in the first place.

Downgrading to 1.19 and a Jenkins restart fixed the issue for now, so it's not super urgent. But I wanted to let you know, that the new overwritable build name feature probably needs some additional work.

**Comment by scaytrase** [comment]
Yeah, sounds like a bug, @westarne do you have a possibility to look into this?

**Comment by westarne** [comment]
I actually don't know why this does not work with the other jenkins syntax. It definitely works with the `notifyBitbucket(...)` syntax without specifying a buildName. I will check the source code if I have missed something but I'm most likely not able to check this on an actual Jenkins. Are there already other optional parameters in the problematic syntax? Something that I can use as orientation?

@adrian-at-dmi if you add a buildName does it throw the same error for buildStatus?

**Comment by westarne** [comment]
I am sorry, I could not reproduce the problem. Using the following in v1.20 I had not error and the status was published correctly in Bitbucket:

```groovy
def revision = "<my-revision>"
notifyBitbucket commitSha1: revision, considerUnstableAsSuccess: false, credentialsId: '<some-guid>', disableInprogressNotification: false, ignoreUnverifiedSSLPeer: false, includeBuildNumberInKey: true, prependParentProjectKey: false, projectKey: '', stashServerBaseUrl: '<some-url-to-bitbuckt-server>'
```

Maybe you are using a different version of the pipeline plugins like Pipeline: Declarative or Pipeline: Groovy or something else? We actually have not up-to-date versions of a lot of plugins. Maybe something has changed there which would need adaption in this plugin or your version is even older.

**Comment by adrian-at-dmi** [comment]
> if you add a buildName does it throw the same error for buildStatus?

Sry, I'm unable to test this at the moment. The `notifyBitbucket` is at the start of almost all our pipelines making tests with a (presumably) faulty plugin kind of risky 😉

> Maybe you are using a different version of the pipeline plugins like Pipeline: Declarative or Pipeline: Groovy or something else?

Yes, we are using the most up-to-date versions of these plugins
* Pipeline: Declarative v1.3.9
* Pipeline: Groovy v2.74

Sorry, that I can't be of that much help. Big thanks for all of your hard work though. It's much appreciated 👍

**Comment by westarne** [comment]
Ok, after some research I think it's not really a problem of the new parameters but that no parameter is correctly optional in this plugin right now: https://issues.jenkins-ci.org/browse/JENKINS-52434

I can check to include this correct optional syntax at least for the new parameters but I'm not sure whether I will be able to test this properly. I will definitely try in the next days and respond here.

**Comment by scaytrase** [comment]
Looks like there is some old problems with constructor set here. I will investigate this either

**Comment by tschlue** [comment]
I'm using the notifier in a DSL-Script and I get also an error for 'buildStatus' with 1.20

`12:43:55 ERROR: (ModuleJob.groovy, line 143) the following options are required and must be specified: buildStatus, buildName`

```
        notifyBitbucket
        {
          stashServerBaseUrl('')
          credentialsId('')
          ignoreUnverifiedSSLPeer(false)
          commitSha1('')
          projectKey('')
          prependParentProjectKey(false)
          includeBuildNumberInKey(true)
          disableInprogressNotification(false)
          considerUnstableAsSuccess(false)
        }//notifyBitbucket
```

Works with 1.90

**Comment by r4d1um** [comment]
It looks like it was introduced here : https://github.com/jenkinsci/stashnotifier-plugin/pull/243

I would expect it takes the buildState and the buildName like it was implemented before, for compatiblity reasons. It should not break exisiting pipelines.

**Comment by westarne** [comment]
@r4d1um this was actually described above already. It is working in some environments (in mine for example, where I can run `notifyBitbucket()` with no parameters without any problems). But somehow some syntax variations seem to need an explicit `buildStatus: null` so that this works.
That's why all other parameters have to be explicitly defined as well. That's not really the problem of the new parameters because every parameter of `notifyBitbucket` works like this at the moment.

Parameters like
```
commitSha1('')
projectKey('')
```
should not be mandatory as well, I think.

For now I was not able to recreate this issue locally in a test environment. It seems to always work as intended. I'm still not sure if this error occurs when upgrading to newer Pipeline/Groovy plugin versions or whether some additional plugins might cause or resolve this issues.

**Comment by r4d1um** [comment]
@westarne will try this as well.

**Comment by jpyams** [comment]
If this is any help with testing, I noticed I got [JENKINS-52434](https://issues.jenkins-ci.org/browse/JENKINS-52434) when I called `notifyBitbucket()` outside a `script` block.  When I moved the call within a `script` block, the issue went away.

**Comment by darxriggs** [comment]
To summarize the comments - this is an issue with the **declarative** pipeline syntax, not the scripted pipeline syntax. For a comparison also see https://jenkins.io/doc/book/pipeline/syntax/. Using a `script` block inside a declarative pipeline makes this block using the scripted syntax.
