### ISSUE TITLE
Status in case of multiple commits only returned for newest

### ISSUE THREAD

**Issue by suukit** [jenkinsci/stashnotifier-plugin#247]
Hi,
I configuretd the plugin against our bitbucket server. Whenever there is more than one commit in a build only the newest commit will get the build status set. Is there a way to publish the build status to all involved commits?

tank you in advance
Max

**Comment by scaytrase** [comment]
Using declarative pipelines you can manually notify any commit you want. 

But IMO it's not correct. Build mark says that this particular commit was built and it you checkout this commit - it's ok (or not ok, if build is red). 

All other commits in a single push are not really tested\built. Moreover - these commits even might be inconsistent (for example one commit contains a bug and second commit fixes it - commit with a bug shouldn't be green), so marking every previous commit in a changeset is not giving any confidence that these commits are really good individually

**Comment by suukit** [comment]
Ah, ic. So in case of a merge, the merge-commit will get the build status instead of the n single commits included in the merge.
