### ISSUE TITLE
Pipeline flow get stuck at “Notifying stash” after finishing all stages

### ISSUE THREAD

**Issue by arielman** [jenkinsci/stashnotifier-plugin#260]
Hi
All our CI projects are getting stuck in the Notify stash. eventually, it's passing, but we're trying to understand why it takes so much time. example:

```
17:03:01 Notifying Stash at "https://bitbucket"
17:15:44 Notified Stash for commit with id 925ceb567087f94c5b9d44d1330995860f11d1e5

```what can cause such a delay? Bitbucket (Stash) Notifier Plugin version: 1.4.0

**Comment by scaytrase** [comment]
@arielman 1.4.0 was released 7 years ago. Actual version is 1.20. I can't help you with such old version

**Comment by arielman** [comment]
Ok, I will check this option. but do you think this might cause the issue?

**Comment by scaytrase** [comment]
I really don't know how it intended to work 7 years ago.
