### ISSUE TITLE
Working with Proxy

### ISSUE THREAD

**Issue by alfador1** [jenkinsci/stashnotifier-plugin#264]
Hello,
My question is simple:
Is there a way to make it work with a proxy server besides  setting server for global configuration for Jenkins.

**Comment by scaytrase** [comment]
Yes, it uses built-in jenkins proxy if configured

**Comment by scaytrase** [comment]
https://github.com/jenkinsci/stashnotifier-plugin/blob/122a4770ecc012d347a9bde186fdbc693a6ffd3f/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java#L528-L530

**Comment by alfador1** [comment]
Hey,
Thanks for the quick response.
Our situation is the following:
We want to run a proxy for a specific job.
Is there a way to make your awesome plugin use proxy for our specific build
instead of using the global Jenkins Proxy configuration?
I hope my question makes sense.

Best regards,
Denis hristov

**Comment by scaytrase** [comment]
no, it's not possible. you trying to run a job on agent which is cannot access bitbucket with global proxy?

**Comment by alfador1** [comment]
It is a shared Jenkins. Used for lots of other jobs. The environment cannot access the bitbucket directly, but instead it needs to go through proxy. This is a specific use case for our jobs. We do not want the whole Jenkins to use that proxy. That is the problem

**Comment by alfador1** [comment]
> no, it's not possible. you trying to run a job on agent which is cannot access bitbucket with global proxy?

It can access with global proxy, but we do not want a global proxy, cause it will affect all of our Jenkins. We need a proxy for that pipeline only

**Comment by scaytrase** [comment]
how do you perform checkout on this environment?

**Comment by alfador1** [comment]
We have a variable gitproxy: proxyaddress
I believe that is being added as a parameter for git to know it uses proxy.
So when it checkouts it does 
```
using GIT_ASKPASS to set credentials Company  Bitbucket Service User
Setting http proxy: b2b-http.something.com:8080

```

**Comment by scaytrase** [comment]
If the slave node is under your control you can try to run agent process with envs like this `JAVA_OPTS=-Dhttp.proxyHost=192.168.0.101 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=192.168.0.101 -Dhttps.proxyPort=3128`

**Comment by alfador1** [comment]
No direct access to the agent, but maybe that can be added as an env to the pipeline during runtime?

**Comment by alfador1** [comment]
> If the slave node is under your control you can try to run agent process with envs like this `JAVA_OPTS=-Dhttp.proxyHost=192.168.0.101 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=192.168.0.101 -Dhttps.proxyPort=3128`

Will it take JAVA OPTS from master Jenkins or from slave?

**Comment by alfador1** [comment]
As adviced I changed JAVA OPTS of jenkins agent, but no proxy was used in this case :(

**Comment by alfador1** [comment]
@scaytrase Do you plan to add that feature to the plugin?

**Comment by scaytrase** [comment]
No, currently not. I'd better suggest to support slave node proxy instead of adding separate proxy settings to each plugin. You can try to fill a PR with it if you want to

**Comment by alfador1** [comment]
> No, currently not. I'd better suggest to support slave node proxy instead of adding separate proxy settings to each plugin. You can try to fill a PR with it if you want to

I want, but I'm not a developer
