### ISSUE TITLE
Add Support for notifying Build Logs and Artifacts for Bitbucket Server >7.5

### ISSUE THREAD

**Issue by timblaktu** [jenkinsci/stashnotifier-plugin#265]
Bitbucket Server 7.4 and 7.5 added support for notifying logs and artifacts along with build status. Their docs say you need to use their Bitbucket Server Integration plugin for this to work. It's not yet clear to me whether this is true. I am not, however, finding any new API in their developer docs indicating how this new notification/association is to be done. As the Atlassian plugin isn't that great otherwise (and lacks notably support for PRs), I would like to get support for logs and artifact links using my current cocktail of jenkins plugins, which includes stashNotifier. Is this possible? Is this feature on the roadmap?

https://confluence.atlassian.com/bitbucketserver/view-builds-information-in-bitbucket-server-1014275096.html
https://developer.atlassian.com/server/bitbucket/how-tos/updating-build-status-for-commits/

**Comment by scaytrase** [comment]
Unfortunately, since there is no public documentation how to implement this on our side - I have no idea whether it's possible or now 🤷

**Comment by scaytrase** [comment]
Since there is no interest neither docs provided - closing this
