### ISSUE TITLE
INPROGRESS status missing

### ISSUE THREAD

**Issue by pilisig** [jenkinsci/stashnotifier-plugin#268]
Jenkins doesn't send the INPROGRESS status of any build. The SUCCESS and FAILED status after finishing the build appears however on the Bitbucket UI. I'm using a Bitbucket Team/Project job, the source is of course our Bitbucket server, and the Jenkinsfile is provided by Remote Jenkinsfile Provider plugin from another git repository on the Bitbucket server. 
If I use the script { notifyBitbucket() } method at the start and at the end of the Jenkinsfile then the INPROGRESS status appears correctly, but all status is displayed duplicated at the end. The plugin sends all status (except the INPROGRESS), and the Jenkinsfile notifybitbucket() sends them too, including the INPROGRESS status, that causes the duplicated status display.

The Bitbucket Server Notifier settings under the Manage Jenkins / Configure System menu are:

Server base URL: (URL of our Bitbucket server)
Credentials: (a valid credential to the Bitbucket access)
Ignore unverified SSL certificates: checked
Keep repeated builds in Bitbucket: unchecked
Prepend parent project name to key: unchecked
Disable INPROGRESS notification: unchecked
Consider UNSATBLE builds as SUCCESS notification: checked

The installed Bitbucket Server Notifier (stashnotifier-plugin) plugin version is: 1.20

**Comment by hcbraun** [comment]
The duplicate notification is coming from the Bitbucket Branch Source Plugin. There is another plugin to disable the notification:
https://plugins.jenkins.io/skip-notifications-trait/

**Comment by scaytrase** [comment]
If this is still the case - feel free to reopen issue or post a comment here
