### ISSUE TITLE
Duplicate status notifications

### ISSUE THREAD

**Issue by SirMrDexter** [jenkinsci/stashnotifier-plugin#269]
I have a problem with the bitbucket server notifier plugin we have in Jenkins.
It sends notifications properly for every build. But they are sent in doubles. One with just the build number and the other with a custom build name.

![image](https://user-images.githubusercontent.com/803034/103960950-88b6c600-51a7-11eb-855a-c02911303eff.png)

Any idea as to what may be causing this and how I can fix it?

Thanks

**Comment by scaytrase** [comment]
It maybe duplicated from bitbucket branch provider

**Comment by SirMrDexter** [comment]
@scaytrase I think you are correct. We also use [BitBucket Push and Pull Request Plugin](https://plugins.jenkins.io/bitbucket-push-and-pull-request/) looks like it always sends a notification when the a build is triggered by it.

Found a related issue reported in there
https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/142
