### ISSUE TITLE
Autocomplete shouldn't populate stash notifier config?

### ISSUE THREAD

**Issue by pmv** [jenkinsci/stashnotifier-plugin#27]
We put the userid and password for stash notifier in the global config.  Therefore there is no userid or password in the job configuration.  However, if you edit any Jenkins job, in certain situations, a userid and password will automatically be inserted in the job config.

Steps to reproduce:
1) Use either Chrome or Firefox (didn't test IE), and have the browser save your password on the Jenkins 'login' page
2) Edit any job that has stash notifier and save.  You can edit anything - it doesn't have to be related to stash notifier.
3) Look at the config.xml and see your userid and password in the stash notifier section.

Since the userid and password are hidden under an 'Advanced' button, if you don't have it expanded, you won't even notice this has happened when configuring the page.

One obvious fix is to not have your browser store your credentials, but how do you keep all users from doing that?

Would this work?
http://stackoverflow.com/questions/2530/how-do-you-disable-browser-autocomplete-on-web-form-field-input-tag

**Comment by scaytrase** [comment]
I think the problem will gone with #62 soon
