### ISSUE TITLE
Swappable Client Implementation?

### ISSUE THREAD

**Issue by sghill** [jenkinsci/stashnotifier-plugin#272]
### Dependencies

None

### Feature Request

Hi, I'm interested in making the client implementation swappable, but wanted to check if there was interest first? I believe this could be done in a way that's fully backwards-compatible.

I think the steps would be:
1. Separate the `StashNotifier` class from Apache (for example returning a `JSONObject` instead of `HttpEntity`)
2. Create a `HttpNotifier` interface that has a `DefaultApacheHttpNotifier` implementation with the same behavior as today
3. Define a way to choose an alternate `HttpNotifier` implementation, possibly per-job.

My use-case: I have some other plugins using `OkHttp` with a lot of setup (retry policies, mTLS, timeouts, logging, metrics). Ideally I'd be able to plug that client into the `StashNotifier` so I could get the benefits of this config while users didn't have to change anything.

**Comment by scaytrase** [comment]
Hello, actually I see a good idea to separate client settings (like proxy, TLS and so on) and plugin logic
