### ISSUE TITLE
Unable to Notify Stash After Build

### ISSUE THREAD

**Issue by Blacktiger** [jenkinsci/stashnotifier-plugin#28]
I'm unable to get the stash notification plugin to work. I have the 'Ignore unverifiable SSL certificate' checkbox checked on my project, but I still get this error message in the logs:

SSLPeerUnverifiedException caught while notifying Stash. Make sure your SSL certificate on your Stash server is valid or check the  'Ignore unverifiable SSL certificate' checkbox in the Stash plugin configuration of this job.

**Comment by scaytrase** [comment]
Is this problem still actual since 1.8 and 1.9 have been released?

**Comment by Blacktiger** [comment]
I'm not sure, we've transitioned to Bamboo and I don't have a good test case anymore. I'll close this issue.
