### ISSUE TITLE
"Ignore unverified SSL certificates" does not reflect actual config value

### ISSUE THREAD

**Issue by martinburger** [jenkinsci/stashnotifier-plugin#33]
While the configuration file contains

```xml
<ignoreUnverifiedSsl>true</ignoreUnverifiedSsl>
```

the interface for the Stash Notifier does not check (enable) the checkbox next to "Ignore unverified SSL certificates".

This has the undesirable effect that each time I save a changed configuration, this feature is disabled unintentionally. To avoid this effect, I have to check that option manually which is quite error-prone.

**Comment by scaytrase** [comment]
Is this problem still actual since 1.8 and 1.9 have been released?
