### ISSUE TITLE
Please provide per Jenkins-Project Key setting

### ISSUE THREAD

**Issue by mfriedrich74** [jenkinsci/stashnotifier-plugin#36]
I would like to get the ability the change the KEY-json field which is sent to the Stash server on a per project basis. Basically i want to be able to set the same Key for several Jenkins projects which map to the same Stash repoitory.
The Key should default to the Project name, but be editable.

**Comment by scaytrase** [comment]
This is definetely a newbie task. Not familiar with Java and Jenkins API but tried to implement something. @gruetter, take a look please at #60
