### ISSUE TITLE
Pull Request Notifications

### ISSUE THREAD

**Issue by tombarber** [jenkinsci/stashnotifier-plugin#37]
Hi, I'm trying to configure jenkins jobs that build pull requests and provide feedback on the stash pull request page but so far am unable to get the notification displayed.

The job builds with the refspec +refs/pull-requests/*/merge:refs/remotes/origin/pr/* and is correctly triggered and if i navigate directly to the pull request commit I can see the job success however this is not included in the builds on the pull request itself.

Is the above possible? am I missing something?

Many thanks

Tom

**Comment by tomasbjerre** [comment]
You can use https://github.com/tomasbjerre/pull-request-notifier-for-stash to supply the variables you may need to build the pull request. And as @vassilevsky said, report back to Stash with this plugin using the from-branch commit.

I wrote a blog post about it here: http://bjurr.se/building-atlassian-stash-pull-requests-in-jenkins/

**Comment by scaytrase** [comment]
For now I can only refer two things. 
First is [Automerge build status plugin](https://marketplace.atlassian.com/plugins/com.bolyuba.stash.plugin.stash-build-status-plugin) for Stash. It will display a build status for automerge commit (shadow `refs/pull-requests/*nn*/merge`).
Second is the already mentioned [Stash issue](https://jira.atlassian.com/browse/STASH-3196). Until PR  commits are not part of the PR from stash side - I think we could do nothing logically based.

With the help of the stash plugin I can run units directly on the merged branch. But it is limited only to single build (It does not display stats or build count or so)
