### ISSUE TITLE
Plugin does not seem to use Jenkins no-proxy settings

### ISSUE THREAD

**Issue by hsmanninen** [jenkinsci/stashnotifier-plugin#41]
If proxy has been setup under "Manage Jenkins -> Manage Plugins -> Advanced" the StashNotifier will always try to access the Stash instance through proxy even though it matches the "No Proxy Hosts" wildcard set in the configuration.

https://issues.jenkins-ci.org/browse/JENKINS-24967

**Comment by jazza72** [comment]
Hmmm - I am getting the following in my build:

Failed to notify Stash for commit 9b18636f47172691e4f0cc22b1bf020ecb9813fa ()

I have removed all proxy settings - running 1.7 version of the Stash Notifier.

Is the same issue or a different one?

**Comment by bbaetz** [comment]
Hi, any update on this? I couldn't find a commit that would fix this that I could cherrypick to our instance?
