### ISSUE TITLE
Issue with SSL certificate

### ISSUE THREAD

**Issue by rcomblen** [jenkinsci/stashnotifier-plugin#43]
Hi,

The plugin cannot be made to accept my valid SSL certificate, due to a change in behavior between versions of Apache Httpclient (4.1 works, 4.1.1 doesn't). Httpclient as used by this plugin considers the certificate of another vhost of the webserver rather than the one associated with my servername.

Please have a look at https://issues.apache.org/jira/browse/HTTPCLIENT-1578 and https://github.com/rcomblen/HttpClientRegressionTest for more details.

Apache Httpclient developer suggest to use an alternative implementation, which is not available with version 4.2.5 of the Httpclient currently shipped with Jenkins.

For now, the solution I've taken is to change the classloader behavior for the plugin, following https://wiki.jenkins-ci.org/display/JENKINS/Plugin+Structure

The leads to the following patch:

    commit 8622a0064516a10db4bacc6537c23777dda2d419
    Author: Richard Comblen <richard.comblen@kreios.lu>
    Date:   Wed Nov 12 08:51:03 2014 +0100
    
        Force version of HTTPCLIENT
    
    diff --git a/pom.xml b/pom.xml
    index c75ebf7..d0bfdcc 100644
    --- a/pom.xml
    +++ b/pom.xml
    @@ -68,4 +68,15 @@
     			<url>http://repo.jenkins-ci.org/public/</url>
     		</pluginRepository>
     	</pluginRepositories>
    +<build>
    +  <plugins>
    +    <plugin>
    +      <groupId>org.jenkins-ci.tools</groupId>
    +      <artifactId>maven-hpi-plugin</artifactId>
    +      <configuration>
    +        <pluginFirstClassLoader>true</pluginFirstClassLoader>
    +      </configuration>
    +    </plugin>
    +  </plugins>
    +</build>
     </project>

I'm not sure an action should be taken on your side before Jenkins ships with a newer version of Httpclient, still I want this to be documented, so I open this issue.

**Comment by scaytrase** [comment]
Closing as https://issues.apache.org/jira/browse/HTTPCLIENT-1578 mentions issue is obsolete due to http-client dependency is more fresh than suggested there
