### ISSUE TITLE
Notify Stash even when SCM is not GIT

### ISSUE THREAD

**Issue by Traumeel** [jenkinsci/stashnotifier-plugin#44]
It is kind of a corner case, but I actually need this.

I have a pipeline Unit Tests -> Integration -> System. UT job gets code from GIT, runs unit tests, notifies Stash and archives the workspace. IT and all further jobs use the workspace created by UT job. They do what they suppose to do and try to notify Stash, but fail with "found no commit info". So in any pipeline only the first job submits results to Stash. 

Due to certain inner issues, I can't use GIT in all the steps of the pipeline.

So it would be nice to have an option to inject GIT info from a file to stashnotifier-plugin, if you want to report build results of a job which does not have GIT SCM configured.

Right now my solution to the problem is to use Groovy script to report to Stash. But it is really messy. Really looking for a cleaner solution. Please let me know what you think.

**Comment by scaytrase** [comment]
As far as I understrand plugin logic, you can provide a TokenMacro to stash commit at job's post puild step. something like `${GIT_COMMIT}`. This will notify preconfigured Stash instance with given commit.
