### ISSUE TITLE
Allow safer authentication mechanisms to stash

### ISSUE THREAD

**Issue by TimSoethout** [jenkinsci/stashnotifier-plugin#45]
I'd love to use this functionality, but currently you have to store your username/password in plaintext in the jenkins settings. 

Are there other possibilities to let Jenkins notify Stash without storing credentials on a shared Jenkins server?

The Stash documentation mentions:

    The REST APIs support basic authentication, OAuth and session authentication.

Maybe OAuth is an option?

**Comment by ashmere** [comment]
Any chance of adding support for credentials ids from 
https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin

**Comment by martinda** [comment]
The Git Plugin Post-Build Publisher is able to push merges back to Stash without a user name and password. I assume they use ssh keys(?), because I have put NO credentials in Jenkins and it just works. On the Stash side, I have uploaded the ssh keys of the account running Jenkins and gave that account permissions on the relevant stash repositories. I would like the stashnotifier to work the same way as the Git Plugin when it comes to authentication. Please let us know what you think, is it hard to do, is it long to do? Even better would be to merge this plugin with the Git Plugin Publisher.

**Comment by Tirex** [comment]
@martinda Can you put link on this (Post builder publisher) plugin?

**Comment by martinda** [comment]
I am no expert here, but here is where the GitPublisher pushes to the remote: https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/GitPublisher.java#L246

The PushCommand comes from the GitClient, and the GitClient is created from the GitSCM instance, gitSCM.

And then I traced into the GitSCM and found where it adds the credentials from the build parameters and puts them in the GitClient:
https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/GitSCM.java#L693

That's a starting point I guess.

**Comment by Tirex** [comment]
@martinda 
I think, push to stash repo interact via ssh, it can access to system ssh keys in Stash.

Update build info available only via stash rest api and it required strictly username and password, no way to use auth by ssh key.
https://developer.atlassian.com/stash/docs/latest/how-tos/updating-build-status-for-commits.html

Found discussion on atlassian.com on same topic.
https://answers.atlassian.com/questions/11459869/stash-rest-api-authentication-via-ssh-key

**Comment by realityking** [comment]
Stash now supports OAuth Authentication, this should be a safer alternative to plain user/password. I'm unfortunately no Java developer, but it would be great if this were supported.

**Comment by ashnazg** [comment]
The new plugin mentioned at that Atlassian link... does it seem to imply that a "Server Token" can be generated that a consumer can use as a sole piece of credential for doing things via the REST API, such as updating build status?  If so, then perhaps this is a new avenue for this Stash Notifier to use... ?

**Comment by gruetter** [comment]
Ideally, I'd like StashNotifier to be independent of third party plugins. So I guess OAuth is the way to go. Would anyone be up for the task?

**Comment by SchwaFa** [comment]
Any news regarding this?

**Comment by gruetter** [comment]
There is, actually. Philip Dodds is working on an integration with the credentials plugin ( see https://github.com/jenkinsci/stashnotifier-plugin/issues/56). This is close to completion. Would this help you, too?

Cheers, Georg

**Comment by SchwaFa** [comment]
Great to hear! 
This would help a lot. ;)

**Comment by holmesb** [comment]
Is anyone having trouble with v1.9 and v1.24 of the Credentials plugin?  Stash notification works fine with username & password credentials, but whenever I add a non username & password credential (eg ssh username with private key), it cannot be selected from the Credentials drop-down.

**Comment by grolfcry** [comment]
holmesb, i have the same trouble

**Comment by wburgers** [comment]
Same here
Would be cool if this is fixed so we can use SSH keys.

**Comment by scaytrase** [comment]
I am not sure stash allows HTTP REST API calls with SSH keys

**Comment by wburgers** [comment]
According to the docs, it should be possible with OAuth
In Stash you would create an Apllication Link and specify the public key of a keypair.
Check [here](https://bitbucket.org/atlassian_tutorial/atlassian-oauth-examples) for more info.

**Comment by scaytrase** [comment]
OAuth is not SSH key and more likely can be implemented. But using Application Links for Jenkins is a great pain AFAIK

**Comment by wburgers** [comment]
I know OAuth is not the same as an SSH key, but in the provided example, they use keypairs, which SSH keys also use :wink:.
It would be great to use the same (or a similar) keypair to access the Stash api and not only just the git repo hosted by Stash.
I have no experience with the Application Links, so I don't know.
In our company, all stash accounts are linked to active directory accounts, so I think it is overkill to create an account for Jenkins in Stash.
That is why I want to explore other options.

**Comment by scaytrase** [comment]
Jenkins has built-in SSH keypair as credentials support, so naming RSA keys "SSH" is confusing. Authentication itself does not uses keypair to authenticate, only to create bearer token, which itself is no more safe as plaintext password. You can steal token using MITM in the same manner as you can steal the plaintext password.

But stealing token only grants you limited (defined by configuration) access rights, so it is less valuable. But no more real secure or safe.

As far as I know you can use several user directories in the attlasian products, so you can create dedicated Stash user, i.e `jenkins_notifier` in the local directory with least priority granting this user minimal neccessary permissions.

Application Links will resolve your issue too, but implement and maintain them is a big problem. I'm using [`Jenkins Intergration for Jira`](https://marvelution.atlassian.net/wiki/display/JJI/Jenkins+Integration+for+JIRA) plugin and it has dosens of problems with reverse-proxy, HTTPS and HTTPS->HTTPS configurations. Thats the problem of Application Links themselves.

**Comment by wburgers** [comment]
Sorry for the naming confusion. You are right.

I am not the Stash admin, but I do administer a project. Within the project I can't create a new user.
This is blocked by our admins.
I guess I'll just request a new dedicated user account.

Thanks for your advice and help!
