### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by vassilevsky** [jenkinsci/stashnotifier-plugin#5]
Hello :)
Our systems administrators have enabled HTTPS for Stash.
So the Stash URL changed from `http://` to `https://`.
After that the plugin started to output errors to build logs. Errors said that the web server returned 301 Moved Permanently.
We of course added the "s" letters to job configs. Everything is OK now.
I just report this issue in case you have lots of free time and want to add some kind of "follow redirects" option to the HTTP client you're using.
Thanks!

**Comment by scaytrase** [comment]
Actually, POST requests could not be redirected correctly with HTTP 301. Current implementations of [RedirectStategy](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.httpcomponents/httpclient/4.5/org/apache/http/impl/client/DefaultRedirectStrategy.java#99) reflect this behaviour, so I think there is nothing to do on plugin side
