### ISSUE TITLE
Global configuration not working

### ISSUE THREAD

**Issue by gessnerfl** [jenkinsci/stashnotifier-plugin#52]
When I configure stash notifier locally for a dedicted job the notification is working as expected.
However the global configuration seems not to work.

When I configure stash notifier globally do I also have to configure notifier on the job itself?
Independent if it is configured on the job or not it is not working.
If I configure it on the job without adding anything to the details section I get an authentication error. If I fill the data it is working. If I remove the notifier from the job itself nothing is happening in respect to stash notification.

**Comment by scaytrase** [comment]
You should add notifier step as a *post-build* step to your job. It automatically inherits configuration from global one.
