### ISSUE TITLE
Please add a setting to disable Stash notification _before_ building

### ISSUE THREAD

**Issue by karlins** [jenkinsci/stashnotifier-plugin#53]
Right before start of a building, the plugin is sending a notification to Stash that build is building. If a build is interrupted especially by a groovy script (for example, while terminating duplicate builds started by notifications) the following Stash notification is not sending, so Stash will keep this notification as "Building" forever.

Moreover, the plug-in description does not contains any mention about _pre_-build actions that can not be avoided or disabled.

**Comment by scaytrase** [comment]
You could try [latest build](https://github.com/jenkinsci/stashnotifier-plugin/releases/tag/1.9-alpha2) to check an option which disables pre-build notification. It's off by default for BC.
