### ISSUE TITLE
notification fails when Stash Root Url ends with "/"

### ISSUE THREAD

**Issue by grizzlyecollege** [jenkinsci/stashnotifier-plugin#54]
on jenkins v 1.602 and v 1.8 of the plugin when my URL ends in "/" the notification fails with the message "Failed to notify Stash for commit [HASH]" followed by an unhelpful HTML splat.  If I remove the final "/" the notification succeeds.

I see the plugin is handling the obvious case of just checking for the presence of a final "/" and normalizing the string, so I'm not sure what could be causing the problem.

**Comment by scaytrase** [comment]
@grizzlyecollege Could not reproduse on snapshot version. My stash notifier URL setting is trimmed (`/` removed) on save. Could you reproduse it?
