### ISSUE TITLE
Use credential plugin

### ISSUE THREAD

**Issue by sean-abbott** [jenkinsci/stashnotifier-plugin#56]
I'd like this plugins to use the credentials plugin, because, for instance, I'm being required to provide a client certificate and your plugin doesn't have a way to do that.

**Comment by adou600** [comment]
Me and my team would be also very interested into that feature!

**Comment by matthewbarr** [comment]
Has anyone tried to do this yet?  We're using the token plugin for now, but also have a cert based authentication that is much more compliant w/ our general security protocols.

**Comment by SchwaFa** [comment]
@matthewbarr Which token plugin do you use?
