### ISSUE TITLE
Allow multiple Stash Notifiers per Job

### ISSUE THREAD

**Issue by stevematyas** [jenkinsci/stashnotifier-plugin#61]
Some jobs need to notify more than one Stash instance and in so it would be great if the plugin could be added more than once per Job.

**Comment by scaytrase** [comment]
Could you give more info on use-case for notifying several stash instances? This will work only when building manually and manually setting "Commit SHA-1" option.

**Comment by scaytrase** [comment]
Looks like using pipelines make this possible without any changes here
