### ISSUE TITLE
Build status

### ISSUE THREAD

**Issue by alex131290** [jenkinsci/stashnotifier-plugin#63]
Hi, 
Let's say the i'm pushing a few commits, and build is failing, as i can see the hook is displaying the build status next to the last commit that was made by me.
Is it ok ?
Is there anyway to improve it, we can get all the commits that were made by the same push, and display this notification next to them.
Another thing which i'm not sure that it's possible to implement, is there any way that we can track down the commit that cause the build to fail?

**Comment by scaytrase** [comment]
The git does not know nothing about the 'pushing'. It's operates the commits. So it doesn't separate two pushes with two commits and one push with four ones. It's all about the state, not transitions.
