### ISSUE TITLE
Debug Logs for Rest API Calls?

### ISSUE THREAD

**Issue by markottaviani** [jenkinsci/stashnotifier-plugin#68]
Is there anything available on the Jenkins side for viewing what REST API calls are being generated and sent to Stash?  I'm trying to troubleshoot a weird issue and it would be helpful to see what the JSON being sent looks like.  I haven't been able to find anything in the logs.

**Comment by scaytrase** [comment]
Currently there are no debug capabilities here. You can try [Stash debug logging](https://confluence.atlassian.com/display/STASH/Stash+debug+logging)

**Comment by markottaviani** [comment]
Thanks, turned out my issues were caused by a buggered up instance of Stash DataCenter.
