### ISSUE TITLE
Failed to notify Stash for commit 5c458cc3866a7ebacceec1f28770899c6b637a81 

### ISSUE THREAD

**Issue by marufaytekin** [jenkinsci/stashnotifier-plugin#69]
When we downgrade to 1.7 because of the issue #57, we are getting following error:

```
Failed to notify Stash for commit 5c458cc3866a7ebacceec1f28770899c6b637a81 (<HEAD><TITLE>internal error - server connection terminated</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black"><H1>internal error - server connection terminated</H1><HR>
<FONT FACE="Helvetica,Arial"><B>
Description: internal error - server connection terminated</B></FONT>
<HR>
<!-- default "internal error - server connection terminated" response (502) -->
</BODY>
)
```
Stash Base URL http://git.mydomain.com:7990

Any idea  why am I getting this error?

**Comment by scaytrase** [comment]
could it be related to #41 (fixed in 1.8)?

**Comment by marufaytekin** [comment]
Possible but, with 1.8 we are getting experiencing issue #57. Are you using 1.8?

**Comment by scaytrase** [comment]
I'm using 1.9-snapshot and no proxy configuration, so my use case may not expose your problems

**Comment by scaytrase** [comment]
Have you tried to inspect logs on stash side?

**Comment by marufaytekin** [comment]
I couldn't see anything in the logs because It was trying to go through the proxy. I disabled the proxy and corrected the configuration mistakes. All seems working fine. I attache configuration details of the plugin here in case anyone else experiences similar problems. 
Thanks for your help.
![git-jenkins-plugin-config](https://cloud.githubusercontent.com/assets/1025908/9634498/ab4ce158-519a-11e5-8519-5985c8953b9d.jpg)
