### ISSUE TITLE
Option to postpone in-progress notification to after injection of environment variables

### ISSUE THREAD

**Issue by mkjensen** [jenkinsci/stashnotifier-plugin#72]
We may have a special setup but maybe this suggestion makes sense for others as well.

For us, the notification for a new build being in progress happens too early, before the commit hash is available (provided to stashnotifier-plugin using the commitSha1 parameter). As you can see in the example build output below, the notifer runs before we have injected environment variables (including the necessary commit hash in $revision from version.properties).

We have quite a lot of code which is why we have chosen to have a job that checks out code. Other jobs can then copy (some) artifacts from that job and do their thing. That way, we only check out code once but it means that other jobs needs to have some properties injected.

We have not found a way to postpone the notification to after injection of environment variables, hence this feature request.

```
Started by upstream project "Checkout" build number 53
originally caused by:
 Started by an SCM change
[EnvInject] - Loading node environment variables.
[EnvInject] - Preparing an environment for the build.
[EnvInject] - Keeping Jenkins system variables.
[EnvInject] - Keeping Jenkins build variables.
[EnvInject] - Injecting as environment variables the properties content 
GIT_REPO=<removed>
BRANCH_NAME=master
SB_REVISION=$SB_REVISION
SB_DESCRIPTION=$SB_DESCRIPTION
SB_URL=$SB_URL

[EnvInject] - Variables injected successfully.
[EnvInject] - Injecting contributions.
Building on master in workspace /jenkins/conf/jobs/Compile/workspace
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Failed to notify Stash for commit $revision ({"errors":[{"context":null,"message":"Please specify the changeset id as a 40-character hash","exceptionName":null}]})
Copied 36,061 artifacts from "Checkout" build number 53
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - Injecting as environment variables the properties file path 'folders_sha.properties'
[EnvInject] - Variables injected successfully.
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - Injecting as environment variables the properties file path 'version.properties'
[EnvInject] - Variables injected successfully.
(...)
```

**Comment by scaytrase** [comment]
@mkjensen  As far as I can see CommitSha1 property already supports expanding via Token Macro subsitutions. Is it possible just to pass ${SB_REVISION} (or something other you use as commit id) there?

**Comment by mkjensen** [comment]
Oh, I should probably have removed the SB_ stuff from the example because it's not active in this case.

The problem is that the commit hash is not available until variables have been injected from version.properties (which contains $revision). As you can see in the example that happens after the notifier has been run. I have not found a way to get the environment variable injected earlier because it happens as a build step and the notifier seems to run before build steps.

**Comment by scaytrase** [comment]
Well, actually I see that first EnvInject pass runs *before* stash-notifier.

```
[EnvInject] - Injecting as environment variables the properties content 
GIT_REPO=<removed>
BRANCH_NAME=master
SB_REVISION=$SB_REVISION
SB_DESCRIPTION=$SB_DESCRIPTION
SB_URL=$SB_URL

[EnvInject] - Variables injected successfully.
<...>
Failed to notify Stash for commit $revision ({"errors":[{"context":null,"message":"Please specify the changeset id as a 40-character hash","exceptionName":null}]})
```

Does it have proper variables in it?

**Comment by mkjensen** [comment]
version.properties example:

```
#Thu, 15 Oct 2015 12:02:19 +0200

revision=8cfc0ecc414862c34a3818f223afa63efa693cfc
revisionNumber=53387
revisionAbbreviated=8cfc0ec
branchName=master
buildType=Dev
```

**Comment by mkjensen** [comment]
Yeah, but the very first injection is from Jenkins job configuration "Properties Content". We don't have the version.properties file until we have copied artifacts from another job and injected them.

This part:

```
Copied 36,061 artifacts from "Checkout" build number 53
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - Injecting as environment variables the properties file path 'folders_sha.properties'
[EnvInject] - Variables injected successfully.
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - Injecting as environment variables the properties file path 'version.properties'
[EnvInject] - Variables injected successfully.
```

**Comment by scaytrase** [comment]
Ok, now I've understood the problem. Currently I cannot imaging flexible delaying configuration, so the only option I can suggest - is to implement #53

**Comment by mkjensen** [comment]
Okay. Right now we implemented a quick workaround to just call Stash manually at the right time to set builds in progress. So if I understand you correctly, we may need to keep that and then look into simply disabling the in progress call of stashnotifier-plugin as requested in #53.

Thank you!

**Comment by scaytrase** [comment]
Yep, something like this. I think later it would be possible to implement two steps 
 * build step to notify *inprogress* 
 * post-build step to notify build finish

But I cannot be sure.

Tnank you for your feedback!

Closing in favor of #53

**Comment by scaytrase** [comment]
You could try [latest build](https://github.com/jenkinsci/stashnotifier-plugin/releases/tag/1.9-alpha2) to check an option which disables pre-build notification. It's off by default for BC.
