### ISSUE TITLE
Failed to notify Stash for commit, ({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":null}]})

### ISSUE THREAD

**Issue by anbeque** [jenkinsci/stashnotifier-plugin#78]
Hi,

Stash v3.11.3
Jenkins 1.529
Stash Notifier plugin : tested with both 1.5 and 1.9.0.

This is the error, same thing with v1.5 and v1.9.0 of the Stash Notifier plugin:

Failed to notify Stash for commit xxxx ({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":null}]}).

We are not specifying any value in these fields:

Ignore unverified SSL certificates,
Keep repeated builds in Stash
Override project key
Prepend parent project name to key
Disable INPROGRESS notification

It stopped working after upgrading our Stash server from v2.10.2 to v3.11.3. We tried upgrading the Stash Notifier plugin to the latest version and using the Credentials plugin to do the authenticate, but still getting the same issue.

Would you have any idea about why it does fail? May I'm missing something at config level. Any advise is welcome.

Thanks,
Angela.

**Comment by scaytrase** [comment]
To sort it out you can try to communicate with Curl directly to Stash REST API from the Jenkins node avoiding the Jenkins plugin. If it succeedes - re-check both Global and Job configuration of the Plugin (Authentication options in particular)

**Comment by ma77h1a5** [comment]
Hi,

I can confirm anbeque's issue after my organisation updated both Jenkins and the Stash Notifier plugin (unfortunately I don't know the previously used versions). Current versions are:

Stash  3.8.1
Jenkins 1.642
Stash Notifier plugin : 1.9.0

I observed the following:
If the credentials are specified in the job configuration (regardless if they are also specified in the global configuration or not), I keep getting the error:

Failed to notify Stash for commit xxxx ({"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":null}]}).

If the the credentials are only specified in the global configuration, notifications work.

It seems as if the credentials specified in the job configuration are not (or not properly) propagated via the Stash REST API as I get the same error if I call the REST API via Curl without supplying any credentials.

Regards,
Matthias

**Comment by scaytrase** [comment]
Looks more concrete. I'll check this out

**Comment by scaytrase** [comment]
Global and local credentials ID acquiring differs only withing these lines of code

https://github.com/jenkinsci/stashnotifier-plugin/blob/develop/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java#L349-L356

```java
		// Determine if we are using the local or global settings
		String credentialsId = getCredentialsId();
		if (StringUtils.isBlank(credentialsId)) {
			credentialsId = descriptor.getCredentialsId();
		}

		Credentials credentials = CredentialsMatchers.firstOrNull(CredentialsProvider.lookupCredentials(CertificateCredentials.class,
				Jenkins.getInstance(), ACL.SYSTEM), CredentialsMatchers.withId(credentialsId));
```

Either local credentials are not blank or empty select for local credentials does not return blank string.

**Comment by ma77h1a5** [comment]
Strange. Then my theory would imply the credentials ID returned by getCredentialsId() and descriptor.getCredentialsId() differs somehow...

**Comment by scaytrase** [comment]
https://github.com/jenkinsci/stashnotifier-plugin/blob/develop/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java#L674-L677

```java
		credentialsId = getCredentialsId();
		if (StringUtils.isBlank(credentialsId)) {
			credentialsId = descriptor.getCredentialsId();
		}
```

Looks like here the global class field is overriden instead of setting local vairiable. I'll patch it up and provide you a test `*.hpi`

**Comment by scaytrase** [comment]
Github does not allow *.hpi, so here is zipped HPI plugin file. Feel free to install via manual plugin installation option and say if this helps
[stashNotifier-1.10-SNAPSHOT.hpi.zip](https://github.com/jenkinsci/stashnotifier-plugin/files/81515/stashNotifier-1.10-SNAPSHOT.hpi.zip)

**Comment by ma77h1a5** [comment]
Thanks for the quick fix! I will provide feedback as soon as it is installed in our Jenkins test instance.

**Comment by ma77h1a5** [comment]
@scaytrase Unfortunately the problem still occurs with the snapshot version. Are you able to reproduce it somehow?

**Comment by scaytrase** [comment]
I've tried, but I can not.

I've cannot event drop global-level credentials (I'll open another issue for it).

On global level I've specified invalid credentials and empty url.
On job level I've specified valid credentials and correct url.

Notification succeeded.

I have an Idea that this may belong to issue #86 as permission issue (no access to credentials specified in job configuration)

**Comment by stevengssns** [comment]
@scaytrase The issue seems to be related indeed. After doing some testing of my preliminary fix, I hit this issue (which turns out to be the "other issue" I was talking about in #86 ).

It took me some browsing through the code, but I think I might have figured out the issue here. In any case it fixed the issue in my setup.

The problem seems to occur on this line (mentioned above somewhere already), when the request is being created:

Credentials credentials = CredentialsMatchers.firstOrNull(CredentialsProvider.lookupCredentials(CertificateCredentials.class,
                Jenkins.getInstance(), ACL.SYSTEM), CredentialsMatchers.withId(credentialsId)); 

The lookupCredentials method seems to only find the top level credentials, which might nog be so surprising when calling it with Jenkins.getInstance(). I figure this represents the top level Item (of jenkins instance). When replace it with build.getProject() (after adding the "build" parameter to the method signature), I get the correct credentials. I actually get an ordered list of all the visible credentials in the project hierarchy, which is exactly what I would expect. 

I'll try to update my open PR tomorrow to include this possible fix. And maybe some additional cleanup if I'm confident enough.

**Comment by ma77h1a5** [comment]
@scaytrase @stevengssns Thanks to you both for investigating! As soon as a new snapshot is available, I'd be happy to test it in my scenario and provide you feedback.
