### ISSUE TITLE
Connect a wrong IP

### ISSUE THREAD

**Issue by ming9010** [jenkinsci/stashnotifier-plugin#80]
I have set Stash base URL ```http://git.sankuai.com/```(IP Add is ```10.64.xxx.xxx```) in System configuration and Job configuration, it sometimes throws a ```ConnectTimeoutException```, says ```Connect to 192.168.133.20:8888 [/192.168.133.20] failed: Connection timed out```. It is obviously  wrong.
I have also tried to set ```http://10.64.xxx.xxx/```, but the problem is still in there.
The Plugin is ```1.9.0```.

Curiously, the same plugin with the same settings in another Jenkins instance works good, the only different thing is version, ```1.8.0```.

**Comment by scaytrase** [comment]
As soon as both IPs are from private networks - check your DNS settings and infrastructure. This plugin does not manage DNS and relies on default Java network operations - I don't think I can help you here. 

As example you can do `nslookup git.sankuai.com >> nslookup.log` every 5 seconds during some period to check it is a DNS failure

**Comment by ming9010** [comment]
@scaytrase OK, I will try it. Thanks.
