### ISSUE TITLE
Empty Credentials Dropdown

### ISSUE THREAD

**Issue by stevengssns** [jenkinsci/stashnotifier-plugin#86]
Hi,

we are moving to an updated Jenkins environment (latest versions), where my team has received a Folder (com.cloudbees.hudson.plugins.folder.Folder) which we can configure as we wish (e.g. adding and configure jobs, credentials, etc..).
Our administrator is using this setup to allow better access control management, which is fine.

However, there seems to be an issue with the StashNotifier, as we are not able to select any of the available credentials, which we are able to configure ourselves on the Folder.
We're certain that the credentials are valid, because we have no problem whatsoever when using the GitSCM plugin. 
Just to be sure I tried just about every possible configuration I could think of (and to which I have access.. I'm not allowed to change the global configuration for instance).
It's most probably some kind of access rights issue, because our administrator could see the credentials that we configured ourselves, while we couldn't.
He could also select one of the credentials, but still they didn't get used by the build.

So I had a quick look at the Git SCM plugin code which lists the credentials:

https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/UserRemoteConfig.java

Line 77: doFillCredentialsIdItems

It definitely does things differently than the StashNotifier does it:

https://github.com/jenkinsci/stashnotifier-plugin/blob/develop/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java

Line 497: doFillCredentialsIdItems

The Git SCM plugin is manly using the Item and Item.CONFIGURE to check if a user has sufficient permissions, while the Stash Notifier plugin is using ItemGroup and Computer.CONFIGURE.

I don't have enough knowledge about Jenkins Plugin development to see what's going wrong here, but the issue seems to be (a.o) located here.
Any reason for this different implementation, and has anyone else observed this behaviour?

If necessary, our Jenkins administrator will be able to provide more detailed information about the setup after the holidays.

Kind Regards,
Steven

**Comment by scaytrase** [comment]
stash-notifier accepts only plain user/pass credentials, not all types. Check your crenendials have some of them

**Comment by stevengssns** [comment]
I'm using simple "Username with password" credentials, so that shouldn't be a problem.

**Comment by scaytrase** [comment]
thats right, I'll try to investigate.

**Comment by scaytrase** [comment]
This really looks like odd permission checking. 

@pdodds what do you think of this as Credentials implementor?

**Comment by stevengssns** [comment]
Fyi, when given slave configuration rights, the dropdown is filled with the configured credentials. This seems to concur with the lines of code that I posted earlier.

![image001](https://cloud.githubusercontent.com/assets/1157521/12016074/abc6562a-ad46-11e5-8b73-129a6ce67899.png)

At that point I still got another error when actually trying to notify Stash, but I don't know if this is related or not. As this security setting is not a viable workaround, I'm not yet going to investigate this further.

**Comment by scaytrase** [comment]
@stevengssns Yes, its definetely related to permissions you've mentioned. I'll review the checking section to have more correct permissions checks during the holidays. PR is also welcome, but this time I think we need documented reference alongside :)

**Comment by stevengssns** [comment]
@scaytrase Thanks for feedback. 

If I was more confident when it comes to Jenkins plugins I might consider a PR, but I'm afraid I'm not.

Enjoy the holidays!

**Comment by scaytrase** [comment]
PR is for credentials bug. Feel free to open another bug to discuss your second issue.

**Comment by stevengssns** [comment]
Ah, feel free to ignore any mention of it. I'm not even sure it is an issue.

**Comment by storjarn** [comment]
I'm having the same issue on a fresh Jenkins installation using homebrew on OSX.  Stash notifier in job configuration and system configuration both have empty creds dropdowns, even though I have creds saved that work with the SCM plugins fine.

**Comment by scaytrase** [comment]
@storjarn Accepting credentials for SCM plugins does not mean they suits other plugins.

StashNotifier could be fed only with high-quality plain credentials only. Stash REST API does accept this kind only

**Comment by storjarn** [comment]
I'm not sure I understand what you are getting at when you say things like "could" and "high quality plain credentials only".

I forgot to make it known I was only referring to ssh creds in my case, since I don't have access to the user password.  Do you mean stash notifier doesn't support certain types of creds like ssh?  :(

In the end, I was trying to help by giving more clues.  Specifics will do us both well.

**Comment by scaytrase** [comment]
sure it does not use ssh keys. it involves stash rest api, which works over http and eats only plaintext creds via basic auth. tokens are possible with 3-rd party stash plugin but are not supported by stash-notifier

**Comment by scaytrase** [comment]
I'll update the readme to make it more clear. I thought it was mentioned there, but not.

**Comment by storjarn** [comment]
Excellent!  Thanks for the heads up.  This gives me a reason to petition for the user password up the chain of command now.  :)

**Comment by stevengssns** [comment]
Hi, I made an attempt to fix the issue, and tested it on a setup that is somewhat similar to the one we have internally.
I only tested the filling of the credentials dropdown, and not the real Stash integration, because I don't have a Stash instance running.

**Comment by scaytrase** [comment]
you can run local standalone stash\bitbucket server by getting [Atlassian SDK](https://developer.atlassian.com/docs/getting-started/set-up-the-atlassian-plugin-sdk-and-build-a-project) and running like [`atlas-run-standalone --product stash`](https://developer.atlassian.com/docs/getting-started/set-up-the-atlassian-plugin-sdk-and-build-a-project/explore-the-installed-sdk-and-the-atlas-commands#ExploretheInstalledSDKandtheatlasCommands-Step3:Tryanatlascommand)

Also you can run local jenkins with plugin with `mvn hpi:run`

**Comment by stevengssns** [comment]
I'll try to run the docker container from atlassian with Stash on it, as I'm running jenkins in one aswel.

**Comment by stevengssns** [comment]
I managed to test the integration with a local Stash instance, even though I first had to find a (possible) fix for issue #78. See my comments over there.

**Comment by GauravJShah** [comment]
FYI, faced this issue today after upgrading Stash Notifier Plugin to 1.10.2 from 1.9.0
Jenkins ver. 1.609.3
Credentials Plugin 1.24

Downgrading Stash Notifier Plugin to 1.9.0 and Creditials Plugin to 1.23 (wasn't sure of the cause of the issue) and restarting has fixed the issue now.

Planning to upgrade the credentials plugin back to 1.24 later in the week, might consider upgrading the Stash plugin again to 1.10.2 next week if i get an opportunity.

**Comment by scaytrase** [comment]
@GauravJShah should be strange, as issue present in 1.9 and should be fixed in 1.10. Open another issue if you face it on upgrade.
