### ISSUE TITLE
[JENKINS-32324] Let stashnotifier plugin be able to resolve a url of scm which contains jenkins global property.

### ISSUE THREAD

**Issue by youjenli** [jenkinsci/stashnotifier-plugin#88]
Inorder to maintain the url of bitbucket server(stash) which was required by several jenkins projects, I decided to define url of bitbucket server as a jenkins global property in the system configuration, and refer to it later at jenkins project.  

![stashnotifier_config](https://cloud.githubusercontent.com/assets/1283378/12172586/ce22f1d0-b58c-11e5-8b9c-b8d4680d2bcf.png)

The interpolation of global property works fine during the pulling of source code by git plugin.  
But it seems that stash notifier plugin can not resolve url which contains jenkins global property, 
thus any build which have to connect to a global-poperty-contained url will fail when stash notifier attempts to notify the "In progress" status to Bitbucket server.  

![stashnotifier_plugin](https://cloud.githubusercontent.com/assets/1283378/12172588/d2a350b0-b58c-11e5-99d1-75c5d04ba260.png)

I hope stash notifier can be able to recognized a url which contains global property in future patch.

**Comment by scaytrase** [comment]
Expanding token is not so hard. To be quick PR is welcome, you can see expanding of commit SHA for reference.

I'll try to get time for this later.

**Comment by scaytrase** [comment]
Expanding tokens in stash url should be supported now with #153 with closest release
