### ISSUE TITLE
Allow multiple commits notified per server

### ISSUE THREAD

**Issue by scaytrase** [jenkinsci/stashnotifier-plugin#90]
Replace #87 

Commits should support TokenMacro, loading from workspace and possible Groovy evaluated script (returning list of commit SHAs)

**Comment by pielu** [comment]
Another scenario when Stash is being notified more than just for the checked / build repository is when (global) shared libraries are defined (since they are checked out as well over scm). The functionality to define what should yield Stash notification is greatly anticipated! :-)

**Comment by riy** [comment]
> Another scenario when Stash is being notified more than just for the checked / build repository is when (global) shared libraries are defined (since they are checked out as well over scm). The functionality to define what should yield Stash notification is greatly anticipated! :-)

You can find a workaround for a part of that  issue over [here](https://github.com/jenkinsci/stashnotifier-plugin/issues/173#issuecomment-574112284).

**Comment by scaytrase** [comment]
I think pipelines is a way to go for this problem.
