### ISSUE TITLE
Notifications not sent when using Build Flow job

### ISSUE THREAD

**Issue by chris5287** [jenkinsci/stashnotifier-plugin#95]
When using the Build Flow job template, pull requests do not get notified on Stash unless the 'Flow run needs a workspace' is ticked.

**Comment by scaytrase** [comment]
could you examine build log for any kind of exceptions, or it does not work silently?

**Comment by chris5287** [comment]
The output from the job is:

<a href="https://STASH/projects/OAK001/repos/vbs/pull-requests/8" >PR #8 Feature/OAK001 70 store uploaded file from stock </a>
Triggered Git URL: https://STASH/scm/OAK001/vbs.git
Triggered Git Commit: 0bc93b37b9740b921e14be6fbaa88d52057e498f
Schedule job OAK001-VBS-BF
Build OAK001-VBS-BF #100 started
OAK001-VBS-BF #100 completed 
Notifying upstream projects of job completion
Finished: SUCCESS

**Comment by chris5287** [comment]
The output from a job that has  'Flow run needs a workspace' ticked contains the line 'Notified Stash for commit with id 0bc93b37b9740b921e14be6fbaa88d52057e498f', so it does look like it is failing silently

**Comment by scaytrase** [comment]
i think plugin can obtain sha to notify only from workspace. I, ll check it later

**Comment by scaytrase** [comment]
i think plugin can obtain sha to notify only from workspace. I, ll check it later

**Comment by scaytrase** [comment]
i think plugin can obtain sha to notify only from workspace. I, ll check it later

**Comment by chris5287** [comment]
did you manage to check this issue?

**Comment by scaytrase** [comment]
I think this even should not work at the moment. Not familiar with Build Flow plugin, but I think this plugins needs some compatibility changes to make it work. Like #92

**Comment by scaytrase** [comment]
Closed in favor of #92 (build flow plugin is marked as deprecated suggesting pipeline one)
