### ISSUE TITLE
Stash notifier 1.10.2 continues to not work with the credentials plugin

### ISSUE THREAD

**Issue by iamkobold** [jenkinsci/stashnotifier-plugin#97]
Getting authorization failure messages from stash and the plug-in doesn't give the option to pick any credentials that are installed on the Jenkins system to use for authorization. 
![screen shot 2016-02-08 at 2 33 52 pm](https://cloud.githubusercontent.com/assets/6364015/12901573/51b184e2-ce71-11e5-9c54-db42c2c87477.png)

Tried this in chrome and safari to rule any weird browser weirdness as well.

**Comment by fvogler** [comment]
I run in the same issue this morning.
Just finished testing a bug fix. PullRequest is in preparation.
Hope it will be accepted. (Need a fix tomorrow)

Regards
Florian

**Comment by eivinhb** [comment]
+1 on this one. Really hope the pull request accepted and released. As it stands now, this plugin i useless for me. :(

**Comment by scaytrase** [comment]
@eivinhb you can found patched plugin in #98

**Comment by eivinhb** [comment]
@scaytrase ah, I did not notice that. Installed and working. Thank you.

**Comment by ckulla** [comment]
Experience this issue as well

**Comment by michaelajr** [comment]
I have the same issue. This prevents the plugin from being used. Any update on a fix date?

**Comment by pgraemer** [comment]
any news here?

**Comment by scaytrase** [comment]
I'll get on fixing test for PR and merge it in a few several days. You can use patched hpi until official release - there should be no difference if PR is OK.

**Comment by McNetic** [comment]
However, it does work with credentials supplied in the build configuration.

**Comment by fongrx7** [comment]
using stash notifier 1.14 version, but still not having the credential in the dropdown. It has the username/password type, but not for the username/private key type.

**Comment by scaytrase** [comment]
because private key is not a way to call HTTP REST API
